### ISSUE TITLE
click_timestamp is 3 hours in future?

### ISSUE THREAD

**Issue by efung** [BranchMetrics/android-branch-deep-linking#214]
We have integrated the Branch SDK into our project. In our `BranchReferralInitListener`, we are passing the referring params up to Mixpanel for tracking. 

On the Mixpanel dashboard, I noticed the value of the `click_timestamp` attribute was `1455130572`. This value is documented to be an epoch time value, but it converts to 18:56:12 (UTC) and 13:56:12 (EST). Since it is currently 11:08:45 (EST), this value appears to be three hours in the future.

I have verified that my device (HTC One M7, Android 4.4.2) has the correct timezone (GMT-05:00, Eastern Standard Time) and correct time set. 

What could be causing this discrepancy?

**Comment by efung** [comment]
FYI, the SDK version we're is `'io.branch.sdk.android:library:1.10.5'`

**Comment by aaustin** [comment]
Hey @efung - sorry for the confusion! That click time stamp is in UTC, as are all raw dates stored in our database. I hope this helps.

**Comment by efung** [comment]
Right, as epoch timestamps are. But interpreted as UTC, the converted timestamp was three hours ahead.
