### ISSUE TITLE
Deep linking not working!

### ISSUE THREAD

**Issue by v-pandiarajan-swaas** [BranchMetrics/android-branch-deep-linking#248]
Hi,
I have clicked the deep linking URL and it takes me to the installed app. But "onInitFinished" callback method always gives me an error. Yesterday itself it's working fine. Please help me to fix this issue.

**Note,**
In test mode it's working fine. 
meta-data android:name="io.branch.sdk.TestMode" android:value="true"
I have tried with 4G & 3G & WIFI.

FYI
**Uri Recieved**
myapp://open?link_click_id=263905820107955258

**Error Log**
Trouble initializing Branch. The server could not complete your request as specified. Please try again at a later time.. Unable to reach the Branch servers, please try again shortly.

**Comment by sojanpr** [comment]
@v-pandiarajan-swaas Can you please  check if you for got to add your live key in your Manifest
`<meta-data android:name="io.branch.sdk.BranchKey" android:value="key_live_my_live_key" />`

Inorder to get a faster response with your implemenataion questions could you please  email your questions to our awesome support team at support@branch.io

**Comment by v-pandiarajan-swaas** [comment]
**My Manifest Settings,**
        ```
<meta-data
            android:name="io.branch.sdk.auto_link_disable"
            android:value="false" />

        <meta-data
            android:name="io.branch.sdk.BranchKey"
            android:value="key_live_iom1TfqjE2ONMpUY9EocahkcCtnckLq2" />

```

Note:
`Same code working when I add <meta-data android:name="io.branch.sdk.TestMode" android:value="true"> to manifest.`

**Comment by sojanpr** [comment]
@v-pandiarajan-swaas can you please make sure you have  the following also added to your manifest
` <meta-data android:name="io.branch.sdk.TestMode" android:value="true" /> <!-- Set to true to use Branch_Test_Key -->`

**Comment by sojanpr** [comment]
@v-pandiarajan-swaas  We had an issue with our service which can give  pride error `Trouble initializing Branch` in some corner cases with the latest version of our SDK. We have updated our server with the fix   an hour before. Could you please try creating link now with live key.
Sorry for the issue

**Comment by v-pandiarajan-swaas** [comment]
@sojanpr Thanks for your response. I have checked It's working now. I need to check further cases and will close this issue once done.

**Comment by sojanpr** [comment]
@v-pandiarajan-swaas Thanks for testing and updating

**Comment by sojanpr** [comment]
@v-pandiarajan-swaas hope every thing is working fine with the fix. would you like to close  this issue?
