### ISSUE TITLE
onNewIntent() is getting called twice

### ISSUE THREAD

**Issue by MouliMohanN** [BranchMetrics/android-branch-deep-linking#257]
If there is a bug or error in this repo, please file the issue here. 

If you need assistance integrating a Branch SDK, please email support@branch.io. Thank you.

Im getting 2 callbacks onNewIntent(). on 1st callback, I dont get any params from Branch, on 2nd callback, I get all params which are supposed to

**Comment by sojanpr** [comment]
@MouliMohanN Thanks  for reaching out. Branch provide the deep link parameters with `BranchReferralInitListener` callback. (Not `onNewIntent()`) .So could you please add the following  code to your activity  `onStart()` method to get the parameters 
``` branch.initSession(new Branch.BranchReferralInitListener(){    
            @Override
            public void onInitFinished(JSONObject referringParams, BranchError error) {
                    // Handle the deep link params here
            }
        }); ```

**Comment by sojanpr** [comment]
For a getting  a faster response on your implementation questions could you please write to our awesome support team support@branch.io
