### ISSUE TITLE
Custom domain name (android)

### ISSUE THREAD

**Issue by eGorets** [BranchMetrics/android-branch-deep-linking#268]
I set up custom domain name in Branch dashboard, but it doesn't redirect me into my app, only to the Play store, but if I use default one, it opens my app. I'm trying to catch URI Scheme `myscheme://` 
and 

    <data
                    android:scheme="http"
                    android:host="my.site.com"
                    android:pathPrefix="/" />

also I can add any other filters to try to solve this issue, but my question is should it work in the way I described above?

Thanks for any help.

**Comment by EvangelosG** [comment]
Hi eGorets,

Here's an example of a functional intent filter for both basic URI scheme deep linking (the first one you'll see in the file) and App Link deep linking (the second one): https://github.com/BranchMetrics/Branch-Example-Deep-Linking-Branchster-Android/blob/master/app/src/main/AndroidManifest.xml

It looks like you're trying to setup App Links, in this case:

` <data android:scheme="https" android:host="bnc.lt" android:pathPrefix="/xhsd" />`
bnc.lt should be replaced w/ your custom domain (assuming you aren't using bnc.lt). And "/xhsd" should be the pathPrefix value copied from the Link Settings page of your Branch Dashboard. If you are on Branch's app.link domain, you will not need to include the pathPrefix portion. Which means that your statement would come out to: `<data android:scheme="https" android:host="my.site.com" /> `

If this does not help, please e-mail integrations@branch.io and I'll be able to offer more involved assistance.

**Comment by eGorets** [comment]
@EvangelosG thanks, I've just sent more details to email

**Comment by stephen-workpop** [comment]
@eGorets When we use our own custom domain, does that mean we need to set up the assetlinks.json and all of that on our own servers? Or is providing our SHA fingerprints on the Branch dashboard enough?

**Comment by eGorets** [comment]
@stephen-workpop I think SHA fingerprints are enough, but you also have to update CNAME on your server
