### ISSUE TITLE
Deep Linking not working when the app is background (opened)

### ISSUE THREAD

**Issue by ronaldo-getreveel** [BranchMetrics/android-branch-deep-linking#270]
Hi, 
Branch is working fine when the app is closed. When I click on the link the second time and the app is in background the `setIntent(Intent intent)` is not called and the onStart method as well. 

My is properly configured with `android:launchMode="singleTask"` and the `onNewIntent()` method as well. 

Any suggestion?

**Comment by ianujag** [comment]
@ghost How did you resolve?
