### ISSUE TITLE
NullPointerException at io.branch.referral.ShareLinkManager

### ISSUE THREAD

**Issue by drusak** [BranchMetrics/android-branch-deep-linking#274]
I'm using branchUniversalObject.showShareSheet() with ShareSheetStyle. And now I see in my crashes the following one inside branch.io:

```
Fatal Exception: java.lang.NullPointerException
       at io.branch.referral.ShareLinkManager$1.onItemClick(SourceFile:189)
       at android.widget.AdapterView.performItemClick(AdapterView.java:299)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1113)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:2911)
       at android.widget.AbsListView$3.run(AbsListView.java:3645)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5095)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

Could you help with it?

**Comment by aaustin** [comment]
Hey @drusak - We haven't seen this before across the network. A couple more questions:
- What SDK version are you seeing this on?
- Are you able to reproduce consistently or is from Crashlytics?
- About what is the frequency?

[Here's](https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/Branch-SDK/src/io/branch/referral/ShareLinkManager.java#L189) the line where it's supposedly crashing. It would appear that somehow Tag is null. However, we set it for every view so I wonder if it's some strange memory management or lifecycle issue that would be pretty rare.

We can issue a patch in the next release which checks for that condition.

**Comment by drusak** [comment]
The version is 1.14.5.
It is from Crashlytics.
Right now it is about 30 crashes, it is quite weird because you set tag for each item, but it is there.
Here is the code We use for sharing
```
public static void shareLink(Activity activity,
                                 String userDisplayName,
                                 int userId,
                                 String feature,
                                 String path,
                                 Branch.BranchLinkShareListener linkShareListener) {
        BranchUniversalObject branchUniversalObject = new BranchUniversalObject()
                .setCanonicalIdentifier(feature)
                .setTitle("Title")
                .setContentIndexingMode(BranchUniversalObject.CONTENT_INDEX_MODE.PUBLIC);

        LinkProperties linkProperties = new LinkProperties()
                .setFeature(feature)
                .addControlParameter("$deeplink_path", path);

        ShareSheetStyle shareSheetStyle =
                new ShareSheetStyle(activity,
                        activity.getString(R.string.hey),
                        activity.getString(R.string.share_string_with_url_template, userDisplayName))
                        .setCopyUrlStyle(android.R.drawable.ic_menu_send, R.string.copy, R.string.copied_to_clipboard)
                        .setMoreOptionStyle(android.R.drawable.ic_menu_search, R.string.more)
                        .setAsFullWidthStyle(true)
                        .setSharingTitle(activity.getString(R.string.share));

        branchUniversalObject.showShareSheet(activity,
                linkProperties,
                shareSheetStyle,
                linkShareListener);
    }
```
Probably it can help you.

**Comment by sojanpr** [comment]
@drusak  Is there a chance that your activity  setting to 
`branchUniversalObject.showShareSheet(activity,
                linkProperties,
                shareSheetStyle,
                linkShareListener);` 
is getting finished by the time user select an item on the sharing item. It seems like the tag is always there   and may be the `context_` is null by that time

**Comment by sojanpr** [comment]
@drusak Created PR with a safe check for the NPE. Could you please check if there is any possibility for the context getting null in your case
https://github.com/BranchMetrics/android-branch-deep-linking/pull/275

**Comment by drusak** [comment]
Thanks, @sojanpr 

These are my thoughts about context null:
context in my case is Main Activity, so potentially it may be null if user close it, but in this case user cannot be able to see the dialog, because your Sharing Sheet is a Dialog with context as a parent.
Also if generating of link is quite long operation (because of some reason), then user closes activity and when link is generated it tries to show dialog with closed activity and it may be cause of NPE. But this is my guess only.

Additional check inside the library is a good thing anyway.
I'll continue to investigate and inform you with details asap. If you have more ideas, I'd appreciate if you share it.

**Comment by sojanpr** [comment]
@drusak Thanks for the update. As you said there should be activity  while the dialog is up. Wondering if there is any chance that the activity reference can be a weak reference. We are trying to replicate the issue. Will update asap

**Comment by drusak** [comment]
@sojanpr 
No, it is an ordinary activity, so user presses the button to share and right there I'm trying to show this branch io dialog with _Activity.this_ object as parameter.

I really appreciate your help!

**Comment by sojanpr** [comment]
@drusak is this issue reproducible at your test environment? If so could you please send the complete log. 
Thanks

**Comment by drusak** [comment]
@sojanpr 
No, but I'm trying to reproduce it, sorry... I'll update you as soon as i get it.

**Comment by sojanpr** [comment]
@drusak Are you using  any configuration changes for your activity like orientation change.  Also could you please update  if you are calling "dismiss()" method for share dialog?

 We have added the safe check against NPE in v2.0.0
