### ISSUE TITLE
Too Bad, 'SingleTask' make app restart when press home

### ISSUE THREAD

**Issue by JinnyZh** [BranchMetrics/android-branch-deep-linking#282]
you use 'SingleTask' for the fist splash activity, that cause the problem

**Comment by EvangelosG** [comment]
Hi JinnyZh,

SingleTask is required to reliably pass deep linked params into an activity. You do not have to use a splash activity as your deep linking activity, that's just one of our samples/examples. Some developers build and style extra invisible activities to deep link into to avoid altering the behavior of their main app's activities.
