### ISSUE TITLE
Branch.BranchReferralInitListener() giving empty JSONObject referringParams

### ISSUE THREAD

**Issue by hardiksharma** [BranchMetrics/android-branch-deep-linking#283]
Using sdk 2.0.2. When trying to do deeplink by clicking shared link, referringParams coming out as empty. 
ex. branch.initSession(new BranchReferralInitListener(){
        @Override
        public void onInitFinished(JSONObject referringParams, Branch.BranchError error) {
            if (error == null) {

Also when tried to check branchUniversalObject, it was giving old params everytime even when clicked the new different link. 

ex. Branch.getInstance(context).initSession(new Branch.BranchUniversalReferralInitListener() {
                    @Override
                    public void onInitFinished(BranchUniversalObject branchUniversalObject, LinkProperties linkProperties, BranchError error) {

**Comment by sojanpr** [comment]
@hardiksharma Sorry that you are facing this  issue. Could you please make sure you have `onNewIntent()` handled in your  activity?

```@Override
    public void onNewIntent(Intent intent) {
        this.setIntent(intent);
    }```

**Comment by hardiksharma** [comment]
Have it already but still see the issue. It only resolves when I add Branch.getInstance().resetUserSession();

**Comment by sojanpr** [comment]
@hardiksharma  It looks to me more like an issue with Branch Automatic  Session implementation. Is there a chance that you missed to add the following to your `Application#onCreate()` method.
```
public final class MyApp extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        Branch.getAutoInstance(this);
        // Uncomment to test memory leak
        // LeakCanary.install(this);
    }
}
```
For getting a faster response could you please  write your implementation issues to our awesome  integration  team integrations@branch.io

**Comment by ronaldo-getreveel** [comment]
Hey there, 
Was published any fix for this issue? The problem started to happening again. :)
