### ISSUE TITLE
JSON key file is missing key prefixes

### ISSUE THREAD

**Issue by stephen-workpop** [BranchMetrics/android-branch-deep-linking#293]
Some of the keys in this file are missing the prefix characters like '+' and "~" in /Branch-SDK/src/io/branch/referral/Defines.java.

For example,         
`Campaign("campaign")`
should be
`Campaign("~campaign")`

I am not sure if this file is supposed to be used externally, but if so, a few of the Enums need to be corrected. If not, could we please get a public file for JSON keys?

Thanks!

**Comment by sojanpr** [comment]
@stephen-workpop Thanks for pointing this. The Defines file is not meant for external usage. We will   make it package locked. We are handling adding `~` internally. Could you please try following method instead
`LinkProperties#setCampaign` or `BranchShortLinkBuilder#setCampaign`

**Comment by stephen-workpop** [comment]
Thanks for the information. I was just trying to read in the incoming referring params so I could log to Mixpanel where each user came from. I'll just use hardcoded strings rather than constants if this constants file is not for public consumption. Thanks!
