### ISSUE TITLE
2.4.0 increased library size over 2.3.0

### ISSUE THREAD

**Issue by kevinzetterstrom** [BranchMetrics/android-branch-deep-linking#298]
2.4.0 brought the inclusion of the android custom tabs library, for use in ```BranchStrongMatchHelper```. This causes the Branch SDK to increase in size considerably because of its new dependencies (com.android.support:customtabs:23.3.0 depends on com.android.support:support-v4:23.3.0). Is there any possibility of removing these in the near future? The raw method count jumps up from around 1400 in 2.3 to over 10k in 2.4 because of the new dependencies. 

Granted us consumers can use ProGuard to try and strip away unused methods, and MultiDex if need be, but it would be nice to be able to consume a lean library.

**Comment by aaustin** [comment]
Hey @kevinzetterstrom - Thanks so much for the note. This was definitely not our intention. We're looking into interim solution to cut out the size, since the bulk of it is not needed and will resort to removing custom tabs if we can't. More soon.

**Comment by aaustin** [comment]
Hey @kevinzetterstrom - We've pushed a fix to the library that removes the unnecessary support v4 dependency, which added the bulk of the size. We had this filtered out in our testbed which is how we missed this.

Can you try the latest and see if this resolves your issue?

**Comment by kevinzetterstrom** [comment]
Looks like this [commit](https://github.com/BranchMetrics/android-branch-deep-linking/commit/7fb24798d06f02a90acc3c73ec907dbb769caae1) was your fix. Unfortunately, this just tries to exclude the dependency. Since custom tabs still depends on support-v4, the dependency isn't actually excluded. I think the only real solution is to remove the custom tabs dependency completely.

**Comment by sojanpr** [comment]
@kevinzetterstrom  Thanks for your comment. 
Actually we are not using any features of custom tab that require `support-v4`. We tested this by eliminating the `support-v4` from the testbed application for this SDK and it seems working fine. Are you using any other lib that uses support-v4? if not could you please check if support-v4 is present in the exploded-aar directory?

**Comment by kevinzetterstrom** [comment]
Ah, I am sorry, the tool I was using to verify this last time must have an issue with it. I used ```gradlew Branch-SDK:dependencies``` and ```gradlew Branch-SDK-TestBed:dependencies``` and it looks good now.

Thank you guys for the quick responses and resolution!

**Comment by sojanpr** [comment]
@kevinzetterstrom  Thank you very much for helping us to improve the SDK
