### ISSUE TITLE
Commit 6d6349a9f1a6f6096ac48882a9662712c7172e4e increases minSdk to 15

### ISSUE THREAD

**Issue by Katkov** [BranchMetrics/android-branch-deep-linking#301]
Hello,

All your documentation says that minSdk is 14, but starting from this commit it is not true anymore.
Please, fix your documentation or return to minSdk 14.

Thank you

**Comment by aaustin** [comment]
Hey @Katkov - Our mistake! Just updated in the readme but also in the documentation portal. Appreciate your keen eye.
