### ISSUE TITLE
Branch init never completes if not using BranchApp as application on Android M+

### ISSUE THREAD

**Issue by shilp-gupta** [BranchMetrics/android-branch-deep-linking#311]
I notice that the init of Branch blocks on handling delayed intents for Android M+. Here - https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/Branch-SDK/src/io/branch/referral/Branch.java#L406

This can only be unblocked by `BranchActivityLifeCycleObserver`. Here - https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/Branch-SDK/src/io/branch/referral/Branch.java#L2217

`BranchActivityLifeCycleObserver` isn't registered if the application isn't set to BranchApp. Here - https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/Branch-SDK/src/io/branch/referral/Branch.java#L513

If using BranchApp is expected to be optional then the source should also not rely upon the application being BranchApp before registering for the activity's lifecycle callbacks.

I don't know if this affects any other users. I especially encountered this when integrating Branch into our Unity3D project and couldn't set the application to BranchApp.

**Comment by sojanpr** [comment]
@shilp-gupta Thanks for reaching out
Branch App is definitely optional  and you need to use that only if you are not  using your own application class. If you are using your own application class please call `Branch.getAutoInstance(application)` from your application's  `onCreate()` method. 
You can see the `LifeCycleObserver ` is registered in this call
https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/Branch-SDK/src/io/branch/referral/Branch.java#L565

Are you missing calling `getAutoInstance()` form your application's `onCreate()` Method?

Also could you please check this  documentation https://github.com/BranchMetrics/android-branch-deep-linking#alt-1-you-have-a-custom-application-class

**Comment by shilp-gupta** [comment]
Hmmm. The unity SDKs documentation didn't mention the requirement to instantiate Branch before the main activity is active (that is, within the Application's onCreate). We are doing this now in our Unity custom application class and it is working perfectly. Thank you.
