### ISSUE TITLE
10k Method Count 

### ISSUE THREAD

**Issue by BugsBunnyBR** [BranchMetrics/android-branch-deep-linking#330]
Hi, it seems branch io sdk has more than 10k methods count ( http://www.methodscount.com/?lib=io.branch.sdk.android%3Alibrary%3A2.%2B ) thanks to support library.

Would it be possible to split the library? I mean, it looks like customtabs is the one to blame and the features that need it could be in some other package.
Thanks.

**Comment by sojanpr** [comment]
@BugsBunnyBR Thanks for pointing  out. We will add handling for excluding the custom tabs if needed. Custom tabs actually provides a way to have very reliable matching guarantee. Thats why we thought it would be great to have it as part of SDK. We will also if there is anything else we can exclude to reduce the method count.

**Comment by sojanpr** [comment]
@BugsBunnyBR  We have made the Chrome custom tabs dependency optional with this PR https://github.com/BranchMetrics/android-branch-deep-linking/pull/338. This will reduce the total number of methods use in the  SDK.
