### ISSUE TITLE
Invalid requests fall through to no connectivity errors

### ISSUE THREAD

**Issue by Kurt-Bonatz** [BranchMetrics/android-branch-deep-linking#331]
Currently in BranchError.java, passing either a status code of ERR_BRANCH_INVALID_REQUEST or an HTTP status code 400 (Bad Request) causes them to fall through the message logic to the default ERR_BRANCH_NO_CONNECTIVITY_STATUS.

 A suggested fix would be to change line 131 from:
`} else if (statusCode > 400) {`
to
`} else if (statusCode == ERR_BRANCH_INVALID_REQUEST || statusCode >= 400) {`

**Comment by sojanpr** [comment]
@Kurt-Bonatz  Thank you very much for helping us to make Branch SDK better. We have opened a PR https://github.com/BranchMetrics/android-branch-deep-linking/pull/333 for addressing  this . Do you think this is good enough?

**Comment by Kurt-Bonatz** [comment]
@sojanpr Looks good for handling the HTTP 400 response code, but you are still ignoring your own status code. I was personally trying to use ERR_BRANCH_INVALID_REQUEST to make a BranchError locally when a url did not pass the whitelisting regex rather than wasting a network request to hear that from the server.

**Comment by sojanpr** [comment]
@Kurt-Bonatz Glad to see that your are using  BranchError for that purpose. Updated the  PR with the fix

**Comment by Kurt-Bonatz** [comment]
@sojanpr Awesome thanks so much for the quick fix and response!
