### ISSUE TITLE
Calling getShortUrl returns long URL if user is offline

### ISSUE THREAD

**Issue by chandsie** [BranchMetrics/android-branch-deep-linking#335]
If you use the `getShortUrl(Context, LinkProperties)` method on a `BranchUniversalObject`, you get back a long URL if the user is offline (because this prevents the SDK from making the network request to create the short URL). I think the SDK should return `null` or indicate an error somehow instead of silently passing in the long URL so that the developer can take some alternate action.

**Comment by chandsie** [comment]
I have a proposed solution in my fork (https://github.com/chandsie/android-branch-deep-linking/commit/f32b184c89675f52a805fb6995b8fd9cdcbc9037) but would love some more thoughts before opening a PR. I imagine there's a case for having this long URL to make sure you don't lose any tracking information in this offline case. I'd argue it's better to give the SDK consumer choice in the matter, but would like to discuss.

**Comment by sojanpr** [comment]
@chandsie  Thank you very much for bringing this up.
 Most of our partners like to get links created 100% of the time when they try to create the link. We have opened a PR https://github.com/BranchMetrics/android-branch-deep-linking/pull/337 which has option to override this for synchronous and asynchronous url creation. It has
```getShortUrl(@NonNull Context context, @NonNull LinkProperties linkProperties, boolean defaultToLongUrl)```
method along with other link creation apis which has the extended control on returning  long url. Would  you mind reviewing the PR?

**Comment by chandsie** [comment]
Left some small stylistic comments, functionally your proposed solution looks great as a fix to this issue. Thank you @sojanpr

**Comment by sojanpr** [comment]
This changes will be added to the next release
