### ISSUE TITLE
Not passing intent data from link to Google Play?

### ISSUE THREAD

**Issue by TOMKHAN** [BranchMetrics/android-branch-deep-linking#336]
Hello.

I've integrated Branch.io in my app. Everything was fine until two/three weeks ago when my users noticed something is wrong with the startup of the app. I'm sending some data via branch.io link, it's leading to the Google Play page of my app. Users then download the app and nothing happens after they enter the app.

I've tested it on Nexus 5 (6.0). It has a problem on first try. But when going back to the link and clicking it again, it all goes as intended. 

Some users have no such problems. I've tested with Nexus 6P (7.0 Android OS), Nexus 7 LTE (6.0), Lenovo P70 (5.0),  Samsung J7 (5.1) and they were all good.

They all use same version of the application. Using 2.4.6 version of Branch SDK.

Does anyone has similar problems?

**Comment by aaustin** [comment]
Hey @TOMKHAN - We have no reports of any issue with the Branch service and nothing has dramatically changed on our side. Would you be willing to write in to our [integrations team](https://support.branch.io/support/tickets/new) and share some details of your account? We'd be happy to review your configuration to help debug!

**Comment by polenchheang** [comment]
Hi We have similar issue and I have send email to integrations@branch.io already. However, If you can provide quick answer, it would be great.

**Comment by TOMKHAN** [comment]
Integrations team noticed this for my case.

I didn't set the same package name in android:scheme (in manifest, as seen below) as in Android URI Scheme on Branch.io dashboard ([Dashboard screen](http://image.prntscr.com/image/ba19db7312ac4960888db3bdbeabf70f.png)). I've aligned them and it seems to me that now, Branch.io is working as intended.

```
<intent-filter>
<data
 android:host="open"
 android:scheme="com.your.app.packagename"/>
<action android:name="android.intent.action.VIEW"/>
<category android:name="android.intent.category.DEFAULT"/>
<category android:name="android.intent.category.BROWSABLE"/>
</intent-filter>
```

**Comment by polenchheang** [comment]
Thanks @TOMKHAN , I configure it correctly. However, Seem like my issue happen because i check getIntent().getData()!=null then initialize Branch and Unexpectedly, it getData==null sometime.

**Comment by sojanpr** [comment]
@polenchheang  For intent `getData` return `null` issue can you please  make sure you are overriding the `onNewIntent()` in case your activity is set to  singleTask launch mode 
``` @Override
    public void onNewIntent(Intent intent) {
        this.setIntent(intent);
    }
```
