### ISSUE TITLE
Firefox Deep Links not opening Android app.

### ISSUE THREAD

**Issue by llDavidll** [BranchMetrics/android-branch-deep-linking#339]
Hi,

I have a branch project linked to an Android and an iOS app. Everything works fine except for Firefox on Android : the link never opens the app, it load in firefox and then opens the Play Store. I have configured my app like this :

<data android:scheme="myscheme" android:host="open"/>
<data android:host="xxxx.app.link" android:scheme="https"/>
<data android:host="xxxx-alternate.app.link" android:scheme="https"/>

I have also set my branch key and it seems to be well configured because it works with the default browser and with Chrome on Android 5 and 6 (with App Links enabled). On both Android versions, Firefox seems to handle `http` and `https` links even if apps can open them.

Is their an issue with firefox or am I missing something in my setup ?

**Comment by EvangelosG** [comment]
Hi David, I'm not able to reproduce any issues regarding Firefox on Android. Can you please submit your case to integrations@branch.io and we can assist you directly? Include your manifest file and I'll point out the potential issue(s).
