### ISSUE TITLE
Should call super.onNewIntent or not call ?

### ISSUE THREAD

**Issue by BugsBunnyBR** [BranchMetrics/android-branch-deep-linking#349]
In the branch io docs there is this snippet...
```java
@Override
public void onNewIntent(Intent intent) {
    this.setIntent(intent);
}
```

Is there any reason to not call `super.onNewIntent(intent)` ?

**Comment by sojanpr** [comment]
@BugsBunnyBR  `onNewIntent` method intension is to provide the  nee intent to the  "singleTop" activities. So we want to set the latest intent as the intent for the activity. So calling super doesnot make sense  in this case

More over  `onNewIntent` method is Activity class is not doing anything
```
 protected void onNewIntent(Intent intent) {
    }
```

**Comment by zackd** [comment]
this is clearly an error in the documentation: https://docs.branch.io/apps/android/#initialize-branch

the Kotlin example calls super.onNewIntent(), but the java example does not
