### ISSUE TITLE
APP Links doesn't work

### ISSUE THREAD

**Issue by SuperQb** [BranchMetrics/android-branch-deep-linking#350]
it is showing an Open With… dialog.

**Comment by SuperQb** [comment]
```
 <intent-filter android:autoVerify="true">
 	<action android:name="android.intent.action.VIEW" />

 	<category android:name="android.intent.category.DEFAULT" />
 	<category android:name="android.intent.category.BROWSABLE" />

 	<data
 		android:host="home.app.link"
 		android:scheme="https" />
 </intent-filter>
```

**Comment by SuperQb** [comment]
![image](https://cloud.githubusercontent.com/assets/18204147/20454873/120ef6ca-ae87-11e6-8c52-41ae98d4da75.png)

![image](https://cloud.githubusercontent.com/assets/18204147/20454875/2418b360-ae87-11e6-9129-c3519fe0f0d3.png)

**Comment by SuperQb** [comment]
![image](https://cloud.githubusercontent.com/assets/18204147/20454880/775cd286-ae87-11e6-8047-b26c5412e31d.png)

**Comment by sojanpr** [comment]
@SuperQb Inorder  for Android to auto verify your app link association your app need an entry is Google's DLA(Digital asset linking file). Branch is doing that for you when you provide your SHA256 finger print for keystone.
Please go to settings -> link in Branch dashboard and make sure you check `Enable App Link`  option and enter  debug / live key store SHA256 finger print.

**Comment by SuperQb** [comment]
@sojanpr I check Enable App Link option and enter debug  key store SHA256 finger print.But it is showing an Open With… dialog.

**Comment by sojanpr** [comment]
@SuperQb Have you enabled this just now? It may take some time to update
the DAL

**Comment by sojanpr** [comment]
@SuperQb is it working now. For a faster response on integration issues could you please write to our awesome integration team integrations@branch.io

**Comment by SuperQb** [comment]
@sojanpr  it is working.Thank you.
