### ISSUE TITLE
Method post must have a request body

### ISSUE THREAD

**Issue by annakozy2011** [BranchMetrics/android-branch-deep-linking#355]
I am integrating a new application with branch, and I am working from Titanium SDK. However, this error does not seem to be related to Titanium. I receive this in the log: 

11-27 18:10:10.101: I/BranchSDK(6084): posting to https://api.branch.io/v1/open
11-27 18:10:10.101: I/BranchSDK(6084): Post value = {
11-27 18:10:10.101: I/BranchSDK(6084):     "device_fingerprint_id": "331447806059763446",
11-27 18:10:10.101: I/BranchSDK(6084):     "identity_id": "331447806282057870",
11-27 18:10:10.101: I/BranchSDK(6084):     "is_referrable": 1,
11-27 18:10:10.101: I/BranchSDK(6084):     "app_version": "2.6.4",
11-27 18:10:10.101: I/BranchSDK(6084):     "facebook_app_link_checked": true,
11-27 18:10:10.101: I/BranchSDK(6084):     "update": 1,
11-27 18:10:10.101: I/BranchSDK(6084):     "debug": true,
11-27 18:10:10.101: I/BranchSDK(6084):     "metadata": {},
11-27 18:10:10.101: I/BranchSDK(6084):     "hardware_id": "38e7ea56-9e77-4cf8-acbd-9f55a90a617c",
11-27 18:10:10.101: I/BranchSDK(6084):     "is_hardware_id_real": false,
11-27 18:10:10.101: I/BranchSDK(6084):     "brand": "samsung",
11-27 18:10:10.101: I/BranchSDK(6084):     "model": "SM-G920F",
11-27 18:10:10.101: I/BranchSDK(6084):     "screen_dpi": 640,
11-27 18:10:10.101: I/BranchSDK(6084):     "screen_height": 2560,
11-27 18:10:10.101: I/BranchSDK(6084):     "screen_width": 1440,
11-27 18:10:10.101: I/BranchSDK(6084):     "wifi": true,
11-27 18:10:10.101: I/BranchSDK(6084):     "os": "Android",
11-27 18:10:10.101: I/BranchSDK(6084):     "os_version": 23,
11-27 18:10:10.101: I/BranchSDK(6084):     "country": "RU",
11-27 18:10:10.101: I/BranchSDK(6084):     "language": "ru",
11-27 18:10:10.101: I/BranchSDK(6084):     "local_ip": "192.168.1.36",
11-27 18:10:10.101: I/BranchSDK(6084):     "external_intent_extra": "{\"windowId\":2,\"windowPixelFormat\":0,\"useActivityWindow\":true,\"finishRoot\":false,\"windowFlags\":0}",
11-27 18:10:10.101: I/BranchSDK(6084):     "cd": {
11-27 18:10:10.101: I/BranchSDK(6084):         "mv": "-1",
11-27 18:10:10.101: I/BranchSDK(6084):         "pn": "com.buznezzcard2.bznz"
11-27 18:10:10.101: I/BranchSDK(6084):     },
11-27 18:10:10.101: I/BranchSDK(6084):     "instrumentation": {
11-27 18:10:10.101: I/BranchSDK(6084):         "v1\/open-brtt": "21",
11-27 18:10:10.101: I/BranchSDK(6084):         "v1\/open-qwt": "0"
11-27 18:10:10.101: I/BranchSDK(6084):     },
11-27 18:10:10.101: I/BranchSDK(6084):     "sdk": "android2.5.1",
11-27 18:10:10.101: I/BranchSDK(6084):     "retryNumber": 0,
11-27 18:10:10.101: I/BranchSDK(6084):     "branch_key": "key_live_XXXXXXXXXXX"
11-27 18:10:10.101: I/BranchSDK(6084): }
11-27 18:10:10.101: I/System.out(6084): (HTTPLog)-Static: isSBSettingEnabled false
11-27 18:10:10.101: I/System.out(6084): (HTTPLog)-Static: isSBSettingEnabled false
11-27 18:10:10.111: I/BranchRemoteInterface(6084): Exception: method POST must have a request body.

**Comment by annakozy2011** [comment]
This issue dissappeared after I have reset my branch key.

**Comment by aaustin** [comment]
Hey @annakozy2011 - How did you reset your Branch key here? Can you list the steps?

We've had this issue apparently on Titanium for a long time and have never been able to reproduce or provide a solution: https://github.com/BranchMetrics/titanium-branch-deep-linking/issues/45

**Comment by annakozy2011** [comment]
No, I did it on Branch Dashboard. 

I am having the issue again though.

**Comment by annakozy2011** [comment]
Now that I cannot reset the key on the dashboard anymore, I changed the key to the test key. 
The issue was gone. 

Changed back to live - reappeared :(
