### ISSUE TITLE
Branch Always returning the wrong ~referring_link

### ISSUE THREAD

**Issue by raheeladnan** [BranchMetrics/android-branch-deep-linking#364]
I am facing the same issue as mentioned in [#352](https://github.com/BranchMetrics/android-branch-deep-linking/issues/352), we are not using it with Facebook SDK. onInitFinished(JSONObject referringParams, BranchError error) the referingParams always give us wrong ~referring_link.

When I test it on https://api.branch.io/v1/url?url= the URL is correct but SDK somehow returns wrong ~referring_link. 
Tried SDK version 2.5.4 and 2.5.3.

**Comment by EvangelosG** [comment]
Hi @raheeladnan -- please contact us through integrations@branch.io so we can reproduce and resolve your issue. I'll make sure to post our findings here for others.

**Comment by EvangelosG** [comment]
Will re-open and comment solution when I make contact w/ ^

**Comment by raheeladnan** [comment]
@EvangelosG the issue is resolved now, you can update this.
Thanks
