### ISSUE TITLE
Docs suggest using singleTask

### ISSUE THREAD

**Issue by rt2zz** [BranchMetrics/android-branch-deep-linking#367]
This is simply, a question. The docs say to [use singleTask](
https://github.com/BranchMetrics/android-branch-deep-linking#register-an-activity-for-direct-deep-linking-optional-but-recommended) however I have seen singleTop work as well, and a [cursory read of the issues](https://github.com/BranchMetrics/android-branch-deep-linking/search?q=singleTop&type=Issues&utf8=%E2%9C%93) suggests other people are using singleTop as well.

Is it ok to use singleTop? are there any gotchas we should look out for?

**Comment by EvangelosG** [comment]
SingleTask guarantees that only once instance of an activity can exist, singleTop does not. SingleTop can lead to multiple instances of the same deep linking activity running. The gotcha would be more than once instance of the activity you're deep linking to existing in your stack. You should do what works best for your app's design, assuming nothing interferes with our SDK passing data through.
