### ISSUE TITLE
cant auto open the app 

### ISSUE THREAD

**Issue by heiyeliuying** [BranchMetrics/android-branch-deep-linking#369]
This is a very strange issue (in **Test** model)。

When i click the deep link from browser ,nothing is happen (I hope the app can open auto).
 But when i restart my app with clicking my app icon ,it still can catch the deep link request ......

ps: I check it many times again follow https://dev.branch.io/getting-started/sdk-integration-guide/guide/android/ ,and didn't find any issue..

below is the  config :

 ```
 <meta-data
            android:name="io.branch.sdk.BranchKey"
            android:value="key_live_fnqgotT6Y1mMLBraxJTNGkpkuFiydToo" />
        <meta-data
            android:name="io.branch.sdk.BranchKey.test"
            android:value="key_test_oaBdesM7WYkHIwxfvTO6tklatBlzmPgs" />
        <meta-data
            android:name="io.branch.sdk.TestMode"
            android:value="true" />
```

```
<activity
            android:name=".loading.LoadingActivity"
            android:screenOrientation="portrait"
            android:launchMode="singleTask"
            >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter>
                <data android:scheme="F.A.Wholesale"  />
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
            </intent-filter>
        </activity>

```

.............................................

Android URI Scheme : **F.A.Wholesale://**

Android version : **5.0.1**

Branch Test link : https://fawholesale.test-app.link/fixed_activity

**Comment by EvangelosG** [comment]
Hey @heiyeliuying ,

When you say nothing is happening, are you being redirected to your fallback URL? Default URL? How are you testing the link? From which app are you clicking it? Which browser are you opening the link with? Chrome has issues w/ pasting links directly into the address bar. It's usually best to test clicking links from Hangouts or Gmail.

I would remove the periods from your URI scheme both in the manifest file and in your Dashboard. Make sure your package name aligns with your Dashboard setting for Test `com.faws.fawholesale` -- also your Test Dashboard has App Links enabled but no information provided (SHA256), this should be disabled or completely filled out. After making sure that these settings align, if you are still having trouble, please contact me through integrations@support.io (with the title "github problem for Evan"). From there we can 1:1 debug and I'll post the resolution here.

When confirming that your package name aligns with what you saved in your Dashboard, make sure your android studio isn't swapping package names via build flavors. Also, data being delivered after you open the app is expected, we just need to remedy the launching bit!
