### ISSUE TITLE
NP exception when clicking on sharing title

### ISSUE THREAD

**Issue by mittalharsh2810** [BranchMetrics/android-branch-deep-linking#370]
In App Sharing when i clicked on Sharing title(which is setsharingtitle("Sharing Using") )  it gives me this error please help me solve it.

  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.CharSequence android.content.pm.ResolveInfo.loadLabel(android.content.pm.PackageManager)' on a null object reference
                                                                       at io.branch.referral.ShareLinkManager.invokeSharingClient(ShareLinkManager.java:236)
                                                                       at io.branch.referral.ShareLinkManager.access$400(ShareLinkManager.java:31)
                                                                       at io.branch.referral.ShareLinkManager$1.onItemClick(ShareLinkManager.java:197)
                                                                       at android.widget.AdapterView.performItemClick(AdapterView.java:315)
                                                                       at android.widget.AbsListView.performItemClick(AbsListView.java:1193)
                                                                       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3231)
                                                                       at android.widget.AbsListView$3.run(AbsListView.java:4214)
                                                                       at android.os.Handler.handleCallback(Handler.java:815)
                                                                       at `android.os.Handler.dispatchMessage(Handler.java:104)`
                                                                       at android.os.Looper.loop(Looper.java:207)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5740)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)`

**Comment by EvangelosG** [comment]
Hi @mittalharsh2810 -- sorry you're having this trouble, would love to dig into this. Can you provide in entirety your share code, so I can reproduce the crash on my end? Does this happen when you share to all apps or just specific app(s)? Also, so I can see exactly what you're doing/sharing to, please make a small recording of the crash, it's super simple and the file will be small. 

Once plugged into your machine w/ USB debugging enabled, open terminal and issue the following:

adb shell screenrecord /sdcard/movie.mp4
//reproduce crash
//(Press Ctrl-C to stop)
adb pull /sdcard/movie.mp4

Once I have this information I'll do my best to reproduce and patch the issue.

**Comment by mittalharsh2810** [comment]
I have attached video please find out and i am sending my code also

BranchUniversalObject branchUniversalObject = new BranchUniversalObject()
                        .setCanonicalUrl("http://www.nearet.com")
                        .addContentMetadata("product", mProductId)
                        .setCanonicalIdentifier("product/" + mProductId)
                        .setTitle(shareTilte)
                        .setContentDescription(description)
                        .setContentImageUrl(firstImageUrl)
                        .setContentIndexingMode(BranchUniversalObject.CONTENT_INDEX_MODE.PUBLIC)
                        .setContentType("application/vnd.businessobjects")
                        .setPrice(mProductRecord.getPrice(), CurrencyType.INR)
                        .addKeyWord(productName)
                        .addContentMetadata("product", mProductId);

                branchUniversalObject.listOnGoogleSearch(ProductDetailActivity.this);

                LinkProperties linkProperties = new LinkProperties()
                        .addTag("productShare")
                        .setChannel("app")
                        .setFeature("sharing")
                        .setStage("10")
                        .setCampaign("Android campaign")
                        .addControlParameter("$desktop_url", getString(R.string.website_url))
                        .addControlParameter("$ios_url", getString(R.string.website_url));


                //noinspection deprecation
                ShareSheetStyle shareSheetStyle = new ShareSheetStyle(ProductDetailActivity.this, shareTilte, shareMsg)
                        .setCopyUrlStyle(getResources().getDrawable(R.drawable.nr_copy_content), getString(R.string.action_copy_clipboard), getString(R.string.copy_clipboard))
                        .setMoreOptionStyle(getResources().getDrawable(R.drawable.nr_other), getString(R.string.other))
                        .addPreferredSharingOption(SharingHelper.SHARE_WITH.EMAIL)
                        .addPreferredSharingOption(SharingHelper.SHARE_WITH.MESSAGE)
                        .addPreferredSharingOption(SharingHelper.SHARE_WITH.WHATS_APP)
                        .addPreferredSharingOption(SharingHelper.SHARE_WITH.FACEBOOK)
                        .addPreferredSharingOption(SharingHelper.SHARE_WITH.GMAIL)
                        .setAsFullWidthStyle(true)
                        .setStyleResourceID(R.style.Share_Sheet_Style)
                        .setSharingTitle(getString(R.string.share_using));

                branchUniversalObject.showShareSheet(ProductDetailActivity.this, linkProperties, shareSheetStyle, new Branch.BranchLinkShareListener() {

                            @Override
                            public void onShareLinkDialogLaunched() {
                            }

                            @Override
                            public void onShareLinkDialogDismissed() {
                            }

                            @Override
                            public void onLinkShareResponse(String sharedLink, String sharedChannel, BranchError error) {
                            }

                            @Override
                            public void onChannelSelected(String channelName) {

                            }

                        },
                        new Branch.IChannelProperties() {
                            @Override
                            public String getSharingTitleForChannel(String channel) {
                                return channel.contains("Messaging") ? shareTilte :
                                        channel.contains("Slack") ? shareTilte :
                                                channel.contains("Gmail") ? shareTilte : null;
                            }

                            @Override
                            public String getSharingMessageForChannel(String channel) {
                                return channel.contains("Messaging") ? shareMsg :
                                        channel.contains("Slack") ? shareMsg :
                                                channel.contains("Gmail") ? shareMsg : null;
                            }
                        });

check video on : https://drive.google.com/open?id=0Bwa8QUlYz--SX2VFQ2I3Y0kyd1RjZnBhZmt5YzdNVGtjYldB

**Comment by EvangelosG** [comment]
hey @mittalharsh2810 -- thanks for your patience over the holidays! I have been able to reproduce your issue. While I dig into this, as a workaround, please comment/remove
`.setSharingTitle(getString(R.string.share_using));` as pressing the `Share Using` button triggers the crash, but it has the same functionality as pressing `Other` which does not trigger a crash. Let me know if that helps.

**Comment by EvangelosG** [comment]
Hey @mittalharsh2810 I created a branch with your potential share sheet title fix, please test and let me know how it goes : https://github.com/BranchMetrics/android-branch-deep-linking/tree/sharesheettitlefix

**Comment by mittalharsh2810** [comment]
yes this is working now but i have to add full sdk for that i just want gradle file for compile not full sdk.
Will you release for that ?

**Comment by EvangelosG** [comment]
I will include this in our next release, thank you for confirming @mittalharsh2810 :)
