### ISSUE TITLE
Crash: io.branch.referral.Branch$BranchWindowCallback.dispatchKeyEvent

### ISSUE THREAD

**Issue by dbharani** [BranchMetrics/android-branch-deep-linking#372]
Fatal Exception: java.lang.IllegalStateException:  
http://crashes.to/s/3a4ba58f020

Please check the crash log in the above link.

Thanks
Deepak

**Comment by EvangelosG** [comment]
Hi @dbharani -- are you on the latest version? We removed window callbacks a bit ago. Let me know if using the latest version (2.5.5 - https://github.com/BranchMetrics/android-branch-deep-linking/releases) helps!

**Comment by EvangelosG** [comment]
Hi dbharani -- I've come to understand that you are using Segment (this repo https://github.com/BranchMetrics/Segment-Branch-Android), and that my colleagues are assisting you directly over e-mail. Let's continue to work directly through e-mail as this could confuse our native Android users.
