### ISSUE TITLE
If you want to use Branch IO with proguard you need to add extra lines in proguard-rules.pro

### ISSUE THREAD

**Issue by MKevin3** [BranchMetrics/android-branch-deep-linking#373]
Even if you do the following in build.gradle

    // Branch IO for deep linking minus the Fabric support
    compile ('io.branch.sdk.android:library:2.5.3') {
        exclude module: 'answers-shim'
    }

You also need to add this to your proguard-rules.pro file to be able to build

# Branch IO usage of crashlytics but we don't use it and exclude it
-dontwarn com.crashlytics.android.answers.shim.**

This should be added to the readme.md file so others don't have to figure out how to get it to compile.

**Comment by sojanpr** [comment]
@MKevin3  Thanks for the note. Will update this to the readMe

**Comment by mikemee** [comment]
Related to #385 - perhaps this is the correct fix, not changing `answers-shim` to `answers.shim`?

**Comment by sojanpr** [comment]
updated the README with the above trouble shooting tips
https://github.com/BranchMetrics/android-branch-deep-linking/commit/11a81f799296cf9d6968e05c1e03a23b720ef12a
Thanks for the helps
