### ISSUE TITLE
Cache deeplinks

### ISSUE THREAD

**Issue by BugsBunnyBR** [BranchMetrics/android-branch-deep-linking#389]
I don't know if BranchIO already have this, but would it be possible to enable cache to the enabled deep 
Links to avoid network errors or even network calls?

**Comment by EvangelosG** [comment]
Hi @BugsBunnyBR -- great inquiry! We cache links **per session** to prevent duplicate requests with the same data payloads. Take a look at https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/Branch-SDK/src/io/branch/referral/Branch.java#L421
