### ISSUE TITLE
Crash in io.branch.referral.SystemObserver.getAppVersion()

### ISSUE THREAD

**Issue by snijsure** [BranchMetrics/android-branch-deep-linking#391]
I am using the  branch library 2.5.6 and I see following crash, is this known issues?
I am suddenly getting these crashes.

`02-08 10:21:35.272 22931-22931/com.myapp.mytravelapp W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String io.branch.referral.SystemObserver.getAppVersion()' on a null object reference
02-08 10:21:35.272 22931-22931/com.myapp.mytravelapp W/System.err:     at io.branch.referral.ServerRequestRegisterOpen.onRequestSucceeded(ServerRequestRegisterOpen.java:97)
02-08 10:21:35.272 22931-22931/com.myapp.mytravelapp W/System.err:     at io.branch.referral.Branch$BranchPostTask.onPostExecute(Branch.java:2655)
02-08 10:21:35.273 22931-22931/com.myapp.mytravelapp W/System.err:     at io.branch.referral.Branch$BranchPostTask.onPostExecute(Branch.java:2516)
02-08 10:21:35.273 22931-22931/com.myapp.mytravelapp W/System.err:     at android.os.AsyncTask.finish(AsyncTask.java:667)
02-08 10:21:35.273 22931-22931/com.myapp.mytravelapp W/System.err:     at android.os.AsyncTask.-wrap1(AsyncTask.java)
02-08 10:21:35.273 22931-22931/com.myapp.mytravelapp W/System.err:     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
02-08 10:21:35.273 22931-22931/com.myapp.mytravelapp W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
02-08 10:21:35.273 22931-22931/com.myapp.mytravelapp W/System.err:     at android.os.Looper.loop(Looper.java:154)
02-08 10:21:35.273 22931-22931/com.myapp.mytravelapp W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
02-08 10:21:35.273 22931-22931/com.myapp.mytravelapp W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
02-08 10:21:35.273 22931-22931/com.myapp.mytravelapp W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
02-08 10:21:35.273 22931-22931/com.myapp.mytravelapp W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

**Comment by EvangelosG** [comment]
Hi @snijsure -- thanks for this report! I've created a branch for you to test a potential fix: https://github.com/BranchMetrics/android-branch-deep-linking/tree/getappversionfix -- let me know how it goes.

**Comment by EvangelosG** [comment]
Hi @snijsure -- looping back here, let me know.

**Comment by snijsure** [comment]
@EvangelosG How do I test code from your branch? Do I check it out, build aar/jar and use it ? Or this branch build is pushed to maven. Eager to test it.

**Comment by EvangelosG** [comment]
Clone the repo -> build AAR -> include in project, should be easiest. If you have trouble I'll send you the AAR! Here's information for including local AARs: http://stackoverflow.com/questions/16682847/how-to-manually-include-external-aar-package-using-new-gradle-android-build-syst

**Comment by EvangelosG** [comment]
Hi @snijsure any results? :)

**Comment by EvangelosG** [comment]
Including this in our next PR, please loop back if the issue was not resolved.
