### ISSUE TITLE
Deep linking not work with gmail native app

### ISSUE THREAD

**Issue by Sonamgupta2109** [BranchMetrics/android-branch-deep-linking#393]
I am trying to open specific page on my app with branch deep link in android. But when click on gmail shared link it did not redirect to app while it works with google+, whats app and twitter.

Please help why is this happen?

**Comment by EvangelosG** [comment]
Hi @Sonamgupta2109 -- happy to look into this, please send your Branch related code (manifest file/activity/application class) to integrations@branch.io and we can examine your integration. If there's a bug I'll make sure to follow up here for others but I suspect there's an integration issue so I'll close for now. If you need an example of an app that deep links correctly from gmail check out this repo https://github.com/BranchMetrics/Android-Branch-Refer-A-Friend-Example

**Comment by EvangelosG** [comment]
Hi @Sonamgupta2109 -- I looked into it, deep linking from Gmail can cause issue without a properly configured URI scheme. Here's directions to configure your app: https://dev.branch.io/getting-started/sdk-integration-guide/guide/android/#register-a-uri-scheme -- and here's an open source app that correctly deep links from Gmail which you can use as a reference: https://github.com/BranchMetrics/Android-Branch-Refer-A-Friend-Example

**Comment by rituapplocum** [comment]
Deep linking not work with gmail native app on Xiaomi and Samsung, it redirects to play store, was working fine few weeks before
