### ISSUE TITLE
Replaces " with \"  of the title append to the BranchUniversalObject

### ISSUE THREAD

**Issue by JustinGeorgeJoseph** [BranchMetrics/android-branch-deep-linking#394]
I have an issue when creating branch link.

When I tried to create a link with double quoted heading like "Nice "Video" bro!". This is show as "Nice \\"Video\\" bro!". I tried many methods but didn't find a nice solution.

Expecting a favorable reply
Thanks,
Justin

**Comment by EvangelosG** [comment]
Hey @JustinGeorgeJoseph -- as we embed the data portion of the link payload inside another json, it's nested and therefore double encoded. From your build.gradle, include `compile 'org.apache.commons:commons-lang3:3.4'` -- in activity just call currentStringWithSlashes = currentStringWithSlashes.StringEscapeUtils.unescapeJson(currentStringWithSlashes) and you'll have the String as you sent it off.
