### ISSUE TITLE
How to integrate deferred deep linking in android

### ISSUE THREAD

**Issue by arushijain45** [BranchMetrics/android-branch-deep-linking#395]
I want to integrate deferred deep linking in my android application so that if app is not installed user can be redirected to specific page after installing it. I searched in the sample but could not find it.

**Comment by sojanpr** [comment]
hi @arushijain45 here is an example for how to get Branch deep link params.
https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/Branch-SDK-TestBed/src/io/branch/branchandroiddemo/MainActivity.java#L314
 There is `+is_first_session` whose value will be true only if this is the first session after installing the app.
 For a faster response on integration related  issues could you please write to our awesome  integration team `integrations@branch.io` for a faster response
