### ISSUE TITLE
IInstallReferrerEvents cannot access in app

### ISSUE THREAD

**Issue by krcho** [BranchMetrics/android-branch-deep-linking#404]
I'm trying to use IInstallReferrerEvents in InstallListener
but that callback message cannot be accessed outside of InstallListener
because it isn't public interface.
So, that interface cannot be used by any class!!

**Comment by sojanpr** [comment]
@krcho  can you please  provide  a little  bit more info on what you are trying to do?
 `IInstallReferrerEvents` is for Branch Internal purpose to get notified when there Install referrer available.  
IN case you want to add your own callback , can you please extend `InstallListener` class and add your own callback. Then yu can override the `onReceive` and call your callback method
