### ISSUE TITLE
Branch.io Android deeplinking not works on Facebook app

### ISSUE THREAD

**Issue by Nickx27** [BranchMetrics/android-branch-deep-linking#411]
Hi Team,
I had created a branch io link to share on facebook and when I'm clicking the link from inside facebook app, it redirects me to the playstore even if the app is installed, but when clicking that link from the desktop browser, it works well(As of now from desktop browser, I preferred to show a deepview). Is there any more configurations I need to set?

Looking forward to your reply,
Thanks.

**Comment by sojanpr** [comment]
@Nickx27  sorry that you are facing this issue. We are checking this issue and update you asap.

**Comment by agrimn** [comment]
Hi @Nickx27 

Sorry to hear that you were seeing this issue, Can you share the Branch link that you are seeing this issue with? For a faster response on your issue please feel free to write into integrations@branch.io

Hoping to resolve this issue asap.

**Comment by Nickx27** [comment]
@agrimn, @sojanpr  : Thanks for the reply, here is the link I'm testing https://ahw7.test-app.link/Qj5XTaVIGB

**Comment by EvangelosG** [comment]
Hey @Nickx27 -- your app isn't available in our country so it's difficult for me to test where your links lead, other than to the Play Store alerting me that I can't download your app. Can you please send your APK file to integrations@branch.io so we can reproduce your issue? If the file size is above 15MB, please send us a google drive download link and grant groth@branch.io read access.

**Comment by Nickx27** [comment]
Sorry @EvangelosG : due to some privacy issues, I can't send the APK.  I'll mail the issue in detail to integrations@branch.io.

Thanks for the support.

**Comment by EvangelosG** [comment]
Was not able to reproduce issue with our sample apps, relayed code to Nick and he's looking into his configuration.

**Comment by Nickx27** [comment]
Thanks for the support team, it works fine now, maybe some mis
configuration in code..

**Comment by EvangelosG** [comment]
Great to hear, thanks for letting us know @Nickx27
