### ISSUE TITLE
initSession and getLatestReferringParams both return empty JSONObject

### ISSUE THREAD

**Issue by nishantpardamwar** [BranchMetrics/android-branch-deep-linking#413]
I'm using android branch sdk 2.5.7

there are two activity in my app 
LoginActivity and MainActivity

LoginActivity is default activity which run first when app is opened.

android manifest : 
```
<activity
            android:name=".LoginActivity"
            android:launchMode="singleTop"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustPan">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter>
                <data
                    android:host="open"
                    android:scheme="xxxxx" />
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
            </intent-filter>
        </activity>
```

im initialising Branch sdk in custom application class

```
public class MyApp extends Application {
@Override
    public void onCreate() {
        super.onCreate();
        Branch.getAutoInstance(this);
    }
}
```

in MainActivity im initialising Branch session

```

@Override
    public void onStart() {
        super.onStart();
        Branch branch = Branch.getInstance();

        branch.initSession(new Branch.BranchReferralInitListener() {
            @Override
            public void onInitFinished(JSONObject referringParams, BranchError error) {
                try {
                    if (error == null) {
                        PrintLog.i("MyApp", "" + referringParams.toString()); // here it is an empty dictionary                     
                    } else {
                        PrintLog.i("MyApp", "error " + error.getMessage());
                    }
                } catch (JSONException e) {
                }
            }
        }, this.getIntent().getData(), this);
    }

    @Override
    public void onNewIntent(Intent intent) {
        this.setIntent(intent);
    }
```

if user is already logged in then LoginActivity opens MainActivity automatically else user has to login first then MainActivity is opened and this is where im having problem if app is opened by a branch link

if app is opened via a branch link and if user is not logged in then after logging-in in MainActivity after initSession or getLatestReferringParams returns empty jsonobject

if user is already logged in then everything is working fine, i cannot figure out what im doing wrong as in docs it is mentioned that i can call **getLatestReferringParams** to get deeplinking params anytime if app is opened by a branch link

**Comment by EvangelosG** [comment]
Hey @nishantpardamwar -- You can see functional examples for how to retrieve data properly in the following repos: https://github.com/BranchMetrics/Android-Branch-Refer-A-Friend-Example - https://github.com/BranchMetrics/Branch-Example-Deep-Linking-Branchster-Android - https://github.com/BranchMetrics/android-branch-deep-linking/tree/master/Branch-SDK-TestBed -- Once you call initSession, init'ing a new session will return an empty payload. You can use getLatestReferringParams (as you saw in the docs) after init session to grab the latest params which are stored in shared preferences, but upon onStop() (navigating away from your app) this function will return an empty payload as well. We suggest using singleTask for deep linking activities vs singleTop, btw. Please play with our example projects to gain an understanding of how to grab branch link data, and note the differences. If you require additional assistance and or think you have discovered a bug, please write in to integrations@branch.io for 1:1 support :).
