### ISSUE TITLE
BranchUniversalObject shortUrl is not working on Chrome app - Android

### ISSUE THREAD

**Issue by eltonealmeida** [BranchMetrics/android-branch-deep-linking#414]
We use  BranchUniversalObject.shortUrl() to referrer users in our app.  This feature used to work fine in all environments till this week. Right now if we try to open the links with **chrome app** on **Android**  we got this error:

The Webpage at market://details?id=my.package.name&referrer=af_tranid%3DvvXBecd3VKjI3Zhw1SkWeg%26pid%3DBranch.io%26c%3DAndroid%26_branch_match_id%3D363034991930648285 might be temporary down or it may have removed permanently to a new web address.

If we choose to open the link with **browser app** on android, the link works.
It seems to be related to the **chrome app** compatibility with **branch.io links**.  It's very high priority because almost all android users set chrome app as default browser

We import your library as suggested, so we don't really:
      compile 'io.branch.sdk.android:library:2.+'

**Comment by EvangelosG** [comment]
Hi @eltonealmeida -- In my experience: clicking a link and selecting Chrome as the app to open it with will not cause error, but pasting Branch links into Chrome's address bar may cause error. If you are able to generate this error by clicking links or following some flow I have not described, this is news to me & please write in to integrations@branch.io so we can take a look.

**Comment by eltonealmeida** [comment]
He @EvangelosG, yes it happens clicking on a link received by e-mail.  I'm writing to you in details on integrations@branch.io

**Comment by EvangelosG** [comment]
Thanks!!

**Comment by EvangelosG** [comment]
For others, the issue here equated to the above partner using a third party redirection link as his $android_url in Dashboard -> Link Settings. Additional redirects placed on-top of our links will cause Chrome to fail.
