### ISSUE TITLE
Duplicate zip entry [com/crashlytics/android/answers/shim/R.class

### ISSUE THREAD

**Issue by rishabh876** [BranchMetrics/android-branch-deep-linking#415]
I am getting the following error due to the new release 2.6.0. 

> Warning:Exception while processing task java.io.IOException: Can't write [/Users/rishabhharit/Documents/GitHub/myproject-android/myproject/build/intermediates/transforms/proguard/release/jars/3/1f/main.jar] (Can't read [/Users/rishabhharit/Documents/GitHub/myproject-android/myproject/build/intermediates/transforms/retrolambda/release/folders/1/1/retrolambda(;;;;;;**.class)] (Can't read [com] (Can't read [crashlytics] (Can't read [android] (Can't read [answers] (Can't read [shim] (Can't read [R.class] (Duplicate zip entry [com/crashlytics/android/answers/shim/R.class]))))))))

Wasted my whole day to figure this out because I was using 
`compile 'io.branch.sdk.android:library:2.+'` 
in my build.gradle.

**Comment by artem-zinnatullin** [comment]
Same here, tried to update to 2.6.0 and got `ZipException: duplicate entry: com/crashlytics/android/answers/shim/R.class`.

We're using fabric answers `1.3.12` and crashlytics `2.6.7`.

@rishabh876 that's one of the reasons why `+` in dependency versions is a bad idea.

**Comment by rishabh876** [comment]
I wouldn't have used '+' if their documentation didn't recommend it.

**Comment by EvangelosG** [comment]
Hey guys, sorry for the headache. Please try including Branch via the following in your build.gradle file:

```
compile ('io.branch.sdk.android:library:2.+') {
  exclude module: 'answers-shim'
}
```

And let me know if this resolves your dependency issue.

**Comment by friedger** [comment]
did not work for me because proguard is missing references

**Comment by vsochinsky** [comment]
@EvangelosG tried excluding answers-shim, worked for me!

**Comment by EvangelosG** [comment]
Thanks @vsochinsky . @friedger The above exclusion resolves the duplicate entry. Proguard is another adventure. Please contact integrations@branch.io with all details possible (build.gradle(s) & proguard rules) if you require additional assistance.

**Comment by leodeleon22** [comment]
Hey @EvangelosG I have the problem still here are the libraries that I'm using

```
compile('com.digits.sdk.android:digits:2.0.6@aar') {
        transitive = true;
    }
compile('com.crashlytics.sdk.android:answers:1.3.12@aar') {
        transitive = true;
    }
    compile('com.crashlytics.sdk.android:crashlytics:2.6.7@aar') {
        transitive = true;
    }
    compile('com.crashlytics.sdk.android:crashlytics-ndk:1.1.2@aar') {
        transitive = true;
    }
    compile('io.branch.sdk.android:library:2.+') {
        exclude module: 'answers-shim'
    }
```

and this is the error when building the APK

```
Error:Execution failed for task ':app:transformClassesWithJarMergingForProdRelease'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/crashlytics/android/answers/shim/R.class
```

**Comment by sojanpr** [comment]
@leodeleon22 It looks like the you get multiple answers-shim from `digits` and  `answers` . Can you please try to exclude `answers-shim` from digits also (The same way you do for Branch)

**Comment by leodeleon22** [comment]
@sojanpr I did but I receive an exception because of the missing methods
´´´
Fatal Exception: java.lang.NoClassDefFoundError: com.crashlytics.android.answers.shim.AnswersOptionalLogger
       at com.digits.sdk.android.DefaultAnswersLogger.loginBegin(DefaultAnswersLogger.java:48)
       at com.digits.sdk.android.DigitsEventCollector.authImpression(DigitsEventCollector.java:90)
       at com.digits.sdk.android.AuthClient.startSignUp(AuthClient.java:83)
       at com.digits.sdk.android.Digits.authenticate(Digits.java:103)
       
´´´

**Comment by sojanpr** [comment]
@leodeleon22  Sorry that you still face this issue. I need to check  which config in your dependencies exporting the Answers multiple time. Can you give it a  try by excluding the `answers-shim` form crashlytics . At this point this is not some thing related to Branch SDK

**Comment by tomauty** [comment]
Might not be relevant to most, but for me I had the segment analytics branch integration enabled, so I modified my build.gradle as follows:

```
    compile ('io.branch.segment.analytics.android.integrations:branch:+') {
        exclude module: 'answers-shim'
    }
 ```
And it works.

**Comment by kevinthecity** [comment]
None of the proposed answers worked for me with

```
  // https://fabric.io/kits/android/crashlytics/install
  compile('com.crashlytics.sdk.android:crashlytics:2.6.7@aar') {
    transitive = true;
  }
```

Downgrading to `Branch 2.5.8` from `2.6.0` fixed my problem for now, will check back here for updates (if any)

**Comment by sojanpr** [comment]
@kevin-ingenuity could you please help to debug. Can  you please share you complete dependency list in build.grade

**Comment by kyle-ilantzis** [comment]
@friedger for proguard you could add the following rule

-dontwarn com.crashlytics.android.answers.shim.*
