### ISSUE TITLE
Constantly data consumption

### ISSUE THREAD

**Issue by Max01010101010101** [BranchMetrics/android-branch-deep-linking#421]
Every time the app open, BranchSDK is posting to https://api.branch.io/v1/open something like this:
Post value = {
                                                        "device_fingerprint_id": "378222643939532699",
                                                        "identity_id": "378222643981468983",
                                                        "is_referrable": 1,
                                                        "app_version": "8.9.12.91",
                                                        "facebook_app_link_checked": false,
                                                        "update": 1,
                                                        "debug": false,
                                                        "metadata": {},
                                                        "hardware_id": "199590ccab4af17e",
                                                        "is_hardware_id_real": true,
                                                        "brand": "Genymotion",
                                                        "model": "Custom Phone - 6.0.0 - API 23 - 768x1280",
                                                        "screen_dpi": 120,
                                                        "screen_height": 764,
                                                        "screen_width": 480,
                                                        "wifi": true,
                                                        "os": "Android",
                                                        "os_version": 23,
                                                        "country": "US",
                                                        "language": "en",
                                                        "local_ip": "10.0.3.15",
                                                        "android_app_link_url": "https:\/\/crew.app.link\/open\/grupo\/0a9ds10dw9j90wjsad90",
                                                        "external_intent_uri": "https:\/\/crew.app.link\/open\/grupo\/0a9ds10dw9j90wjsad90",
                                                        "cd": {
                                                            "mv": "-1",
                                                            "pn": "com.enp"
                                                        },
                                                        "google_advertising_id": "3179a998-1369-4155-9b9c-198a7a2a15a5",
                                                        "lat_val": 0,
                                                        "instrumentation": {
                                                            "v1\/close-brtt": "485",
                                                            "v1\/close-lrtt": "85",
                                                            "v1\/open-qwt": "0"
                                                        },
                                                        "sdk": "android2.5.9",
                                                        "retryNumber": 0,
                                                        "branch_key": "key_live_jbAzaN9Ovmuk3uPxdZKkHihmCAiwVaxI"
                                                    }

How can we stop this data collection?

**Comment by EvangelosG** [comment]
Hi @Max01010101010101 -- this data is used/required for session tracking and link data passing. Take a look at our matching documentation https://dev.branch.io/getting-started/matching-accuracy/overview/ -- we try to be as transparent as possible. The data is not sold or shipped to anyone, it's used for matching and your own metrics.
