### ISSUE TITLE
Return back the support of Android API 14+

### ISSUE THREAD

**Issue by alex-dorokhov** [BranchMetrics/android-branch-deep-linking#422]
From the repository history it looks like the Branch SDK 2.x had a support for Android API 14.
However the minSdkVersion was increased to 15 to support chrometabs.
From the implementation and README it looks like chrometabs is now an optional dependency and it is accessed via reflection in the code. That means chrometabs is not a reason of minSdkVersion=15 anymore.
Probably there is no other reason to do not support API 14 by the SDK.

**Comment by sojanpr** [comment]
@alex-dorokhov Thanks for pointing this out. You are right, since the  `ChromeTab` dependency is optional we can support from Android API 14. Will add this change with our next revision.
