### ISSUE TITLE
Malformed Intent Data URI

### ISSUE THREAD

**Issue by pmarino** [BranchMetrics/android-branch-deep-linking#428]
Hi,

We've noticed some issues when parsing deep-links containing a URI fragment / anchor. After integrating the SDK, it looks like the Intent data URI is being updated [[link](https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/Branch-SDK/src/io/branch/referral/Branch.java#L1403)], however is not accounting for URLs containing a fragment with existing query parameters. I believe the URI specification mentions the fragment identifier should always be the last part of the URL.

`http://www.test.com/test?test_param=123#.456&branch_link=true`

Thanks and let me know if you need any additional information!

**Comment by sojanpr** [comment]
@pmarino Thanks for notifying this issue. We are working on it and add support for Fragmented Urls

**Comment by sojanpr** [comment]
@pmarino We have opened a PR (https://github.com/BranchMetrics/android-branch-deep-linking/pull/429) for this issue. Will be shipping this with our next release.
