### ISSUE TITLE
onInitSession callback has wrong referralParams on second click

### ISSUE THREAD

**Issue by edinaleitner** [BranchMetrics/android-branch-deep-linking#433]
Hello, we have this issue on v2.6.1, with the following steps to repro:

1. click on a branch link
2. branch activity starts, initSesssion callback has correct parameters {..., "+clicked_branch_link":true}
3. in the callback we start another activity and finish the current one (branch activity finished)
4. minimize app
5. click the same branch link again
6. branch activity starts, initSession callback has WRONG params {..., "+clicked_branch_link":false}

*Note: if we don't finish the branch activity, and open the other activity above it, everything works as expected, and params are correct for the second time, data not missing. But this is not a desired behaviour, we want to finish the branch activity as soon as the user is redirected to the appropriate screen. Our branch activity is like a splash screen, it is used to decide where the user should be redirected, depending on the referralParams.
*Note: onNewIntent is never called (because before the second click the branch activity is finished)

Sample code from the branch activity:

protected void onStart() {
        .........
        Branch branch = Branch.getInstance();
        branch.initSession((referringParams, error) -> {
               ........
               //start another Activity
               //finish this Activity - if we remove this step, params are ok for the second time
        }
        .....
}

public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        setIntent(intent);
}

**Comment by sojanpr** [comment]
@edinaleitner We are trying  to reproduce this issue on our side. So far no luck. Are you clicking  an app-link or is it opened from a browser ? For a faster response on this integration issues could you please write to integrations@branch.io

**Comment by edinaleitner** [comment]
it is an app-link.

**Comment by poqueque** [comment]
I'm having similar problem. I'm calling initSession with these params:

branch.initSession(new Branch.BranchUniversalReferralInitListener() {
            @Override
            public void onInitFinished(BranchUniversalObject branchUniversalObject, LinkProperties linkProperties, BranchError error) {
...
        }, getIntent().getData(), this);

and the first time works ok, but the second time branchUniversalObject is null.

I have check that the URI given on getIntent().getData() is ok both times.

**Comment by EvangelosG** [comment]
Hi @poqueque -- please write in to integrations@branch.io and we'll take a closer look. Include your Branch related code & steps to reproduce the issue, i.e. are you clicking a second link and getting a null BUO, or clicking one link and then opening the app twice to find the second open returns a null BUO?

**Comment by poqueque** [comment]
I'm clicking twice the same link. Second time on the app it returns a null BUO. I've already contacted that email and waiting for an answer.

**Comment by EvangelosG** [comment]
Thanks @poqueque -- we're taking a look!

**Comment by edinaleitner** [comment]
Hello @sojanpr  @EvangelosG , any news on this?

**Comment by EvangelosG** [comment]
Hi @edinaleitner -- We have not been able to reproduce the issue in house. I see you wrote in to support, thank you, Sojan and I will contact you directly from there, and our findings will be echoed here for others.

**Comment by EvangelosG** [comment]
Sorted through edinaleitner's issue, it related to her activity being destroyed before it was able to init session! Still working with poqueque, 1 down 1 to go! Have relayed a test project for poqueque to play with, fingers crossed.

**Comment by EvangelosG** [comment]
Will re-open this issue if/when I hear back from poqueque -- so far no bugs have been identified.
