### ISSUE TITLE
Release tagging with release notes.

### ISSUE THREAD

**Issue by amardeshbd** [BranchMetrics/android-branch-deep-linking#439]
Hi Guys,

Is there any place I can go to to see release notes for each release?

https://github.com/BranchMetrics/android-branch-deep-linking/releases

> If you need assistance integrating a Branch SDK, please email support@branch.io. Thank you.

**Comment by EvangelosG** [comment]
Hey @amardeshbd -- Yep! Right here: https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/ChangeLog.md
