### ISSUE TITLE
Branch init success, but no link detect

### ISSUE THREAD

**Issue by mousamk** [BranchMetrics/android-branch-deep-linking#440]
This is just a report, so that it may be useful.

I have added branch dependency of version "2.+"; so naturally I was using the latest version. A few while ago, my app stopped tracking all events including "reopens", "installs" except for only "link clicks". When I debugged on my machine, I noticed than regardless of opening app by clicking a branch link or manually from launcher, it doesn't detect "link clicks". The referring params were always like this:

`{"+clicked_branch_link":false,"+is_first_session":false}`

although the intent data was showing the correct clicked url:

`takhfifan://open?link_click_id=392637966397181927`

After one day of debugging and enabling/disabling my app's features, finally I found out that when the branch init call (`Branch.getInstance().initSession(...)`) is concurrent with my app's own network calls (our rest service), it fails to detect link clicks. However, when I disabled our network calls and deferred them to after `initSession()`s return, it was working ok and the "link clicks" were being detected correctly!

I just though maybe this would be worth mentioning.

**Comment by EvangelosG** [comment]
Hi @mousamk -- thanks for bringing this to our attention. It's possible you were testing while we were having Android issues and that your results may be mixed. Either way I have made a note of it, and if you have issues in the future and want to avoid debugging so much on your end, contact integrations@branch.io directly and we'll have a took! Thanks again!
