### ISSUE TITLE
Branch not detecting branch url from sms

### ISSUE THREAD

**Issue by kimv** [BranchMetrics/android-branch-deep-linking#445]
I am using Branch for deep linking into my app. I successfully integrated branch and I am able to handle multiple urls to redirect the user where he needs to go.

However, branch does not detect that an external link was clicked if it was clicked from a SMS. The same url works if I click it from Whatsapp, Skype or email.

This is how I use branch in my activity:

    @Override
    protected void onCreate(Bundle savedInstanceState) {
         super.onCreate(savedInstanceState);
         // bunch of code here
         initBranch();
    }

    private void initBranch(){
        showLoadingDialog();
        Branch branch = Branch.getInstance(getApplicationContext());
        branch.initSession(new Branch.BranchReferralInitListener(){
            @Override
            public void onInitFinished(JSONObject referringParams, BranchError error) {
                dismissLoadingDialog();
                if (error == null) {
                    Log.d(TAG, "on branch init finished -> " + referringParams);
                    try {
                        handleBranchData(referringParams);
                    }catch (Exception e){
                        e.printStackTrace();
                    }
                } else {
                    Log.e("MyApp", error.getMessage());
                }
            }
        }, this.getIntent().getData(), this);
    }

    private void handleBranchData(JSONObject json) throws Exception{
        Log.d(TAG, "handling branch data -> " + json);
        String nonBranchLink = json.optString("+non_branch_link", null);
        boolean clickedBranchLink = json.getBoolean("+clicked_branch_link");
        if(clickedBranchLink){
            String deepLinkPath = json.getString("deeplink_path");
            Uri uri = Uri.parse(deepLinkPath);

            String path = uri.getPath();
            Log.d(TAG, "path from branch = " + path);

            String[] splitPath = path.split("/");
            Log.d(TAG, "branch splitPath[1] = " + splitPath[1]);

            switch (splitPath[1].toLowerCase()){
                case "properties":
                    openPropertyActivity(splitPath[2]);
                    break;
                case "viewings":
                    openViewingActivity(splitPath[2]);
                    break;
                case "offers":
                    openOfferActivity(splitPath[2]);
                    break;
                case "validate":
                    if(splitPath[2].equals("email")){
                        validateEmail(splitPath[3]);
                    }else if(splitPath[2].equals("mobile")){
                        validateMobile(splitPath[3]);
                    }
                    break;
            }
            // todo handle other branch cases

        }else{
            Log.d(TAG, "branch initialized -> nothing was clicked");
        }
    }

If I open the app from the SMS, this is what the logger says: handling branch data -> {"+non_branch_link":"https:\/\/link.pad.co.uk\/ZpGz\/FvbUEOBjMD.","+clicked_branch_link":false,"+is_first_session":false}

If I open the exact same link from Whatsapp, I get: handling branch data -> {"+match_guaranteed":true,"deeplink_path":"https:\/\/staging.wearepad.com\/validate\/mobile\/98391","~creation_source":0,"+clicked_branch_link":true,"+click_timestamp":1496821789,"$one_time_use":true,"~id":400905699091257321,"$one_time_use_used":false,"+is_first_session":false,"~referring_link":"https:\/\/link.pad.co.uk\/ZpGz\/FvbUEOBjMD"}

As you can see, the app recognizez the branch url correctly when it is opened from Whatsapp, but not from SMS. 
Any ideas?

**Comment by EvangelosG** [comment]
Hi @kimv -- I noticed a few things. First, you should init Branch from `onStart()` -- and you should not be passing application context from your Activity. Here's a sample app you can compare your implementation to:  https://github.com/BranchMetrics/Android-Branch-Refer-A-Friend-Example -- if you still have trouble please contact integrations@branch.io and we can review your integration 1:1. Another thing, make sure your deep linking activity is using launchMode=singleTask.

**Comment by kimv** [comment]
@EvangelosG Thank you for your reply. I moved the initBranch() method so that it is called in the onStart() method of the activity. I also changed the initialization of branch to be in the onCreate() method of the Application with Branch.getAutoInstance(this). I checked my manifest, and the activity in question already has launchMode=singleTask. However, the issue still occurs, it works the same as it did before.

I sent an email to integrations@branch.io and I will update this thread ASAP.

Thank you

**Comment by EvangelosG** [comment]
Thanks @kimv I'll respond directly through our integrations portal and will post our findings here.

**Comment by EvangelosG** [comment]
It looks like Kimv's dashboard link settings for Android have not been completed. We are reconfiguring it with Kim now!

**Comment by dianabordei** [comment]
Was this fixed with only dashboard configuring of links? I am asking as I have a similar issue. In my case If I am prompted with a chooser to open the SMS link from Browser or from App, if the App is already open and in background, and I choose it, I don't receive the configured parameters and clicked is false. If I choose the browser it works ok.

**Comment by EvangelosG** [comment]
Hi @dianabordei -- It was fixed in the sense that Kimv did not complete their account's link settings, and once we walked them through these steps, SMS passed link data through correctly (specifically, their App Link settings). Please contact integrations@branch.io so we may examine your account! Also, please make sure you are init'ing Branch from onStart and not onCreate.
