### ISSUE TITLE
BUG -  Branch.isInstantApp() always false on Android O for Instant Apps

### ISSUE THREAD

**Issue by kevinzetterstrom** [BranchMetrics/android-branch-deep-linking#455]
For Android O apps, the Branch.isInstantApp() always returns `false`. If you diff this against the Google Instant App SDK method, the Google method has additional logic for if the device is an Android O device.

**Comment by sojanpr** [comment]
@kevinzetterstrom Thanks for creating this issue. We had the same login from Google at the time of introducing this method. We will check the latest version and update it soon

**Comment by EvangelosG** [comment]
Hi @kevinzetterstrom -- Thanks again for this report. Here's a PR with updated isInstantApp code: https://github.com/BranchMetrics/android-branch-deep-linking/pull/456 -- let me know how it goes, we'll be reviewing & publishing this update next week.

**Comment by kevinzetterstrom** [comment]
Thanks for the quick update, we appreciate it. My only comment on the code is more of a question: are the `Log` statements absolutely necessary?

**Comment by EvangelosG** [comment]
Glad you appreciate it. As for the log statements, they are necessary if you would like to log errors. If not, you can comment them out. I can also make these statements obey the debug/testmode flag so they can be toggled.

**Comment by kevinzetterstrom** [comment]
Cool, we would be using this once a release is cut and it is hosted rather than building an AAR ourselves, so having them obey a flag would be great - this way ProGuard would rip them out.

**Comment by EvangelosG** [comment]
Kk, I've implemented the logic locally. Testing with my own instant app(s) shortly after a company meeting, I'll QA for a bit and get back to you!

**Comment by EvangelosG** [comment]
Hi @kevinzetterstrom -- we're merging and releasing your requested fix today (https://github.com/BranchMetrics/android-branch-deep-linking/pull/456). Again, thank you so much for the report, and let me know if you have any [other] issue(s).
