### ISSUE TITLE
Unable to retry link resolving after fail on bad connection

### ISSUE THREAD

**Issue by dmitry-novikov** [BranchMetrics/android-branch-deep-linking#457]
We use deep-links in process of migration users from one system to another. So it's very crucial for us extract user info from link in any case. 
For the moment, the is no documented way how to retry deep-link resolving (`initSession`) after if fails for the first time in bad connection environment.

**Comment by EvangelosG** [comment]
Hi @dmitry-novikov -- my interpretation is that you want to grab link parameters once internet has been regained. To monitor network state, see this: https://developer.android.com/training/monitoring-device-state/connectivity-monitoring.html -- Now that you can monitor connections, when someone's service returns, you'll have to do a "forceRestartSession" with the initial intent which launched your activity. To accomplish this: 

**1.** Save the original intent.
**2.** Add the following extras to it:
```
i.putExtra(branch_force_new_session.getKey(), true);
i.putExtra(Defines.Jsonkey.BranchLinkUsed.getKey(), true);
```
**3.** Use the original intent to launch your deep linking activity, and it will re-init and grab the link parameters.

**Comment by dmitry-novikov** [comment]
Many thanks for answer.
Is it possible to do this "forceRestartSession" without launching deep link activity at all? 
Launching it can break user experience because he/she can be be in the middle of some process.

**Comment by dmitry-novikov** [comment]
@sojanpr, I do something very similar to what you described but with small modification.

I'm able to resolve deep link using (1) `data` from original Intent of deep link Activity and (2) ANY started activity without setting original Intent to it. And it works even without additional parameters proposed by @EvangelosG. Is it as intended or it's a must to set original Intent into Activity used to resolve?

And by the way, there is kind of bug in Branch sources. Parameter `data` in `initSession` function marked as `@NonNull`, but `Intent.getData()` may return `null`...

**Comment by sojanpr** [comment]
@dmitry-novikov thanks for trying it out. 
Based on your comment I think this is what happening
1) User click a link and deep link activity is launched
2) Branch SDK read the intent data (`Link-click-Id` / `App link` from the deep link activity intent) and  save it locally
3) Branch try to get deep link  data using the intent data saved
4) getting deep link data fails when you don't have internet connection.
5) Launching a new activity with `branch_force_new_session` the steps from 2-4 works again.

So my understanding is that you are getting deep link params in your new activity only because the lntent data is already saved locally form the deep linked activity. This is not a safe assumption so it would be always a good idea  to pass the original intent associated  with deep link activity when you want to restart the session.

As you can see in step 2  Branch need  the intent data  to get deep links params. So if your intent's data is `null` then Branch cannot retrieve the  deep link params. That is the reason for marking the param as `@NonNull`

**Comment by dmitry-novikov** [comment]
@sojanpr, actually our flow to resolve branch deep link is following:
1. A soon as DeepLinkActivity get launched we exstract `data` from Intent and store it in OUR `pendingUri` storage.
2. On ANY activity start (we listen for activities life-cycle via `registerActivityLifecycleCallbacks`) if we have `pendingUri` to process we do `branch.initSession` using this activity and `Uri` from `pendingUri`. And we DO NOT change activity intent because we think that it's bad by design (activity can depend on original intent state and changing it could damage activity logic).
3. If point (2) result is success, then we cleanup `pendingUri` storage and do deep link routing withing the app.
4. If point (2) result is error, then we keep `pendingUri` as is and wait for another activity start, i.e. repeat step (2).

This flow works pretty good. And as you may noticed, we DO NOT apply any flags/data like `branch_force_new_session` into activity's intent because we DO NOT modify original intent of the activity.

The only concern I have about this flow is how deep link from Install Receiver will works (Google Play referrer)?

Could you please evaluate flow I described and comment about Google Play referrer?

**Comment by dmitry-novikov** [comment]
UPDATE. Flow described above doesn't work at all for retrieving deep-link on first launch after install from Google Play. So we have to revert our implementation to proposed by branch solution.

Though it's still not clear how to retry deep-link resolving in such cases (i.e. failed on first launch from GP). It looks like branch stuck on `INSTALL_REFERRER_FETCH_WAIT_LOCK` state after first fail that also blocks subsequent links processing (even with `branch_force_new_session` set).

@sojanpr, @EvangelosG, any suggestions?

**Comment by sojanpr** [comment]
@dmitry-novikov can you please upgrade to SDK v2.10.3 and make sure you are setting the max wait time for play store referrer using API `setPlayStoreReferrerCheckTimeout(long timeOut)`. This will time out waiting for playstore referrer and unlock `INSTALL_REFERRER_FETCH_WAIT_LOCK`.

For a faster response  can you please write to our awesome integration support team at integrations@branch.io

**Comment by EvangelosG** [comment]
Handling this directly over e-mail. No SDK bugs/issues discovered yet. If there are any we'll report back here!
