### ISSUE TITLE
Same link data returned on app restart and first link click is empty

### ISSUE THREAD

**Issue by engineers-bojan** [BranchMetrics/android-branch-deep-linking#461]
We have integrated branch over a year ago and everything was working fine...at least we thought so when we tested the last time around March.

Branch is integrated per docs, autoinstance, and in the activity onStart we init the session with the activity, its data and BranchReferralInitListener.

The first time the link is clicked the BranchReferralInitListener returns empty data on android 7.0 (this also never happened before). I've debugged the Branch code at it seems in the readAndStripParam method the intentState_ is not yet ready.

Note: On android 6.0 the first click returns the clicked data.

But after that every app launch returns that data even though the activity intent data is null!? Debugging the code i can see that the data returned to the listener is getLatestReferringParams() which will read the cached data...but reading throught the docs this data should be cleared when app is restarted. I've checked and all activities are closed so the internal branch activity lifecycle listeners should be aware of this.

Since our gradle link was using 2.+ as the version num i tried using the latest version and a version from from March ( 2.5.9 for ex) but its still happening... Tested on android 7.0 and 6.0.

**The craziest thing? I uninstall the apps, restart the phone, install them from Android Studio and the data is still cached without clicking any links :D ?**

Any clues? (p.s. we have facebook sdk but we arent using any "deeplinking" features etc..also branch is just 
the simplest implementation possible, we share a user id via the BranchUniversalObject)

**Comment by sojanpr** [comment]
@engineers-bojan We are sorry that you are facing this issue. This looks really  strange especially getting data after uninstall. We are testing it and will update soon.

**Comment by sojanpr** [comment]
@engineers-bojan We have tested this case on Android 7 (Samsung galaxy s8). Seems everything work as expected. Can you please help debugging with the following link
 https://branchster.app.link/6LeJADfEeF
This is a  link for out test app which we published in playstore(Code is here https://github.com/BranchMetrics/Branch-Example-Deep-Linking-Branchster-Android).
If this works fine we  can check what is creating issue in your code else could you please provide more details of the device and your test steps

**Comment by engineers-bojan** [comment]
@sojanpr I've tried the demo app with the example link and it works as expected.

I've double checked the implementation just in case, but everything matches the example.

What i've found additionally is that the data resets itself after 5min, as i've i tried repeatedly opening and closing the app and noticed that after a while the data clear.

I've debugged further and found that ServerRequestRegisterOpen executes on app start up and it returns the clicked link data which is then set in prefHelper_.setSessionParams and thus is returned afterward via callback even though no data was sent to the initSession method.  (the ServerRequestRegisterClose is properly executed upon app close and the data in the prefHelper_ is set bnc_no_value)

This leads me to believe that maybe something is wrong with our config in the branch dashboard/console thats keeping the data cached?

**Comment by sojanpr** [comment]
@engineers-bojan  Thanks for trying it and checking your implementation. Our awesome integration team can help you very quickly with  any issue you face with Branch dashboard config. Could you please write to integrations@branch.io

**Comment by engineers-bojan** [comment]
Can you confirm that this issue is related to the dashboard config, as i only mentioned it as a hunch since everything else seems ok...i would also like to add that the configuration hasnt been changed since we first implemented it so i am still skeptical about it and besides there are no caching options in the dashboard or similar.

**Comment by sojanpr** [comment]
@engineers-bojan Since this is happening only for the links to your app and we need to check the links for moving further on this. Suspect there may be a `match_duration` set for the links

**Comment by fahimsakri** [comment]
This is happening with me also in the app.. nothing is changed in the app in branch implementation but couldn't figure out its returning old data, after reinstalling the app, restarting the phone.

**Comment by sojanpr** [comment]
@fahimsakri Are you seeing the old data returned to you after installing the app? It would be really helpful if you are provide the steps you do and the link you are using to figure out the issue. I think we can support this case better with our awesome  integration team. Could you please write to integrations@branch.io and lets resolve it there.
