### ISSUE TITLE
RuntimeException at io.branch.referral.InstallListener.captureInstallReferrer

### ISSUE THREAD

**Issue by jonathankau** [BranchMetrics/android-branch-deep-linking#462]
We use the Branch Cordova SDK v2.6.5 (latest), but are seeing a bunch of native Android crashes in our production app. We haven't been able to reproduce this locally, but we've seen this happen on Android 7.1, 7.0, 6.0 as well as multiple devices such as the Nexus 6P, Galaxy S8, OnePlus3T and more.

Did some digging, and it looks like this is caused by https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/os/Handler.java#200. Thoughts?

Full Stacktrace:
```
java.lang.RuntimeException: 
  at android.os.Handler.<init> (Handler.java:200)
  at android.os.Handler.<init> (Handler.java:114)
  at io.branch.referral.InstallListener.captureInstallReferrer (InstallListener.java:41)
  at io.branch.referral.Branch.registerAppInit (Branch.java:2280)
  at io.branch.referral.Branch.initializeSession (Branch.java:2234)
  at io.branch.referral.Branch.initUserSessionInternal (Branch.java:1238)
  at io.branch.referral.Branch.initSession (Branch.java:895)
  at io.branch.referral.Branch.initSession (Branch.java:969)
  at io.branch.BranchSDK.initSession (BranchSDK.java:234)
  at io.branch.BranchSDK.access$200 (BranchSDK.java:31)
  at io.branch.BranchSDK$RunnableThread.run (BranchSDK.java:1238)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
  at java.lang.Thread.run (Thread.java:761)
```

**Comment by sojanpr** [comment]
@jonathankau the only I can see  this crash can happen when you call `initSession` from a non UI thread. You create handler inside thread that has not called Looper.prepare(). So can you please  make sure the `initSession` is happening on main thread

**Comment by sojanpr** [comment]
@jonathankau Where you able to fix the problem by changing to Main thread?

**Comment by jonathankau** [comment]
@sojanpr Sorry about that, as I mentioned in the initial issue, we're using a wrapper around the native Android branch SDK through Cordova: https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#initialize-branch. Thus, we don't have trigger the native Java code ourselves, the plugin does.

We're following the instructions for the Cordova plugin, but it seems to be causing an error in the native code. Mind seeing if you can pull in one of the Cordova plugin authors?

**Comment by sojanpr** [comment]
@jonathankau we are taking a  look at the cordova sdk. Will update you soon. Can you please update which version of SDK you are using

**Comment by jonathankau** [comment]
@sojanpr We are using the latest version of the Cordova SDK, unless you were asking about the Android SDK? I believe the Android SDK is included as a dependency in the Cordova SDK https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/blob/master/build.gradle#L11, so we should be using the latest Android SDK as well.

**Comment by sojanpr** [comment]
Thanks for that info. We are trying few ways to reproduce it locally. Will keep you posted.

**Comment by ethanneff** [comment]
Hello @jonathankau,

We are still unable to reproduce the crash locally, but when investigating the issue, we noticed that we were calling `Branch.initSession()` from a background thread within the Cordova SDK. This is unneeded because we automatically push the `Branch.initSession()` to a background thread within our Android SDK. By playing around with this assumption, we were able to crash the app with the Branch SDK.

I have pushed a [new version of the Branch Cordova SDK (2.6.6)](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/releases). Can you please [update your Branch Cordova SDK](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-updating-the-branch-sdk) to the latest version to see if the crashes stop?

Thanks,

**Comment by jonathankau** [comment]
I sent an updated APK to an affected user and that new Cordova commit fixed the issue for them. We'll roll out the change to the rest of our users and see whether the crashes completely disappear. Thanks for the quick turnaround time @ethanneff @sojanpr!

**Comment by EvangelosG** [comment]
Thanks for the update @jonathankau -- Please get back to us if the crashes don't completely disappear.
