### ISSUE TITLE
Deep linking stop for Twitter and facebook other other social network it works fine.

### ISSUE THREAD

**Issue by Sonamgupta2109** [BranchMetrics/android-branch-deep-linking#463]
Hi,
Suddenly deep linking stop working for facebook and twitter. Previously it works fine.

Here is my manifest code :

      <meta-data android:name="io.branch.sdk.BranchKey" android:value="key_live_kcugN5uWGMVeX4m9CHLPUfmfzrk5yMDb" />

        <intent-filter android:autoVerify="true">
                <data android:scheme="05media.com" android:host="open" />
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https" android:host="05media2.app.link" />
                <data android:scheme="https" android:host="05media2-alternate.app.link" />
            </intent-filter>

Also i enable custom search and add package name ( com.pinmedia.mediaguide ).
Same use in manifest 
Also add SHA256 Cert Fingerprints.

Please help me why this is not working for twitter and facebook. For other it's work fine

**Comment by EvangelosG** [comment]
Hi @Sonamgupta2109 -- when you say deep linking stopped working, did your app stop opening? Is data no longer being passed? Are you using the Facebook native app, or are you using Facebook through a mobile browser, if so which browser(s)? Also, your intent filter is setup for app links **and** regular deep links, you should be using two intent filters for this scenario as follows:

```
<!-- Deeplink Config -->
<intent-filter>
<data android:scheme="05media.com" />
<action android:name="android.intent.action.VIEW" />
<category android:name="android.intent.category.DEFAULT" />
<category android:name="android.intent.category.BROWSABLE" />
</intent-filter>

<!-- AppLink config -->
<intent-filter android:autoVerify="true">
<action android:name="android.intent.action.VIEW" />
<category android:name="android.intent.category.DEFAULT" />
<category android:name="android.intent.category.BROWSABLE" />
<data android:scheme="https" android:host="05media2.app.link" />
<data android:scheme="https" android:host="05media2-alternate.app.link" />
</intent-filter>
```

Example intent filters: https://github.com/BranchMetrics/Branch-Example-Deep-Linking-Branchster-Android/blob/master/app/src/main/AndroidManifest.xml#L34

You can also check out the above project if you need to compare your implementation to a working one. Another example app lives here: https://github.com/BranchMetrics/Android-Branch-Refer-A-Friend-Example

I have been unable to reproduce any issue regarding launching FB/Twitter using the above projects. If after checking them out you continue to struggle, please contact us directly: integrations@branch.io -- we'll walk through your integration with you!

**Comment by Sonamgupta2109** [comment]
Added these lines but result is the same. I mailed you on  integrations@branch.io please see my issue

**Comment by EvangelosG** [comment]
Thanks @Sonamgupta2109 -- we'll reply from there directly. If any oddities are discovered I'll make sure to report them here for others.
