### ISSUE TITLE
Can't Fetch params with branch deep link iOS

### ISSUE THREAD

**Issue by nitesh-homage** [BranchMetrics/android-branch-deep-linking#473]
I am unable to fetch link properties in iOS (swift) with latest branch sdk. Every time the link properties are not returned but when I try with non-branch link the properties are there. Is this some issue with branch. Its so annoying issue. Can someone please help with that.

```
Branch.useTestBranchKey()
let branch = Branch.getInstance()

branch?.initSession(launchOptions: launchOptions, automaticallyDisplayDeepLinkController: false, deepLinkHandler: { params, error in
		//branch?.initSession(launchOptions: launchOptions, andRegisterDeepLinkHandler: { params, error in
			if let error = error {
				print(error.localizedDescription)
				return
			}
			print(String(format: "params\n%@", (params?.description ?? "")!))
			if let clickedBranchLink = params?[BRANCH_INIT_KEY_CLICKED_BRANCH_LINK] as! Bool?, clickedBranchLink {
			//print("params: \(cpName) and \(visitId)")
				guard let paramsDictionary = (params as? Dictionary<String, Any>) else {
					print("No Branch parameters returned")
					return
				}
				let referringLink = paramsDictionary["~referring_link"] as! String
				let content = String(format:"\nReferring link: \(referringLink)\n\nSession Details:\n\(paramsDictionary.description)")
				
				print(content)
				print(String(format: "Branch TestBed: Finished init with params\n%@", paramsDictionary.description))
			}
		})
```

**Comment by sojanpr** [comment]
@nitesh-homage Sorry that you are facing this issue. I think you wanted to report an issue with iOS sdk (or is there any thing related with Android SDK here?) . We are looking this on our iOS sdk and get back to you soon

**Comment by E-B-Smith** [comment]
@nitesh-homage This looks like a configuration issue.  You can talk with a support engineer at Branch to help you out:  https://support.branch.io/support/tickets/new

**Comment by E-B-Smith** [comment]
Plus, try 
```
Branch.useTestBranchKey = true
```

**Comment by EvangelosG** [comment]
Our support team is working with Nitesh directly over e-mail to resolve this integration issue. If you have follow up iOS inquiries please post on the iOS repo: https://github.com/BranchMetrics/ios-branch-deep-linking
