### ISSUE TITLE
2.12.0 gradle dependency is not resolving

### ISSUE THREAD

**Issue by agramian** [BranchMetrics/android-branch-deep-linking#475]
I just tried updating the version of branch in our project and `2.12.0` is not resolving but `2.11.1` still works fine.

**Comment by EvangelosG** [comment]
Hi @agramian -- thanks so much for bringing this to our attention. Let me dive into the repository manager, I'll sort it out and get back to you.

**Comment by sojanpr** [comment]
Hi @agramian looks like we had a refresh issue with the Sonatype repo. We have refreshed 2.12.0 and made sure it is available in the maven release  channel. Can you please try one more time

**Comment by agramian** [comment]
It still does not seem to be working.

```
Error: Failed to resolve: io.branch.sdk.android:library:2.12.0
```

**Comment by sojanpr** [comment]
@agramian We are checking it and it may take a while to be available. We will be trying it after a  while and update  you.

**Comment by saurabhdtu** [comment]
@agramian 
Its compiling at my end
 compile('io.branch.sdk.android:library:2.12.0') {
        exclude module: 'answers-shim'
    }

**Comment by EvangelosG** [comment]
Looks like it took gradle a bit to update, it's available now! If you still cannot compile please let us know @agramian :)
