### ISSUE TITLE
v2.12.0 Fails to build

### ISSUE THREAD

**Issue by gjsalot** [BranchMetrics/android-branch-deep-linking#476]
I cannot build an app referencing v2.12.0, I get several of the following errors:

io/branch/indexing/AppIndexingHelper references unknown class: com/google/firebase/appindexing/*

Manually forcing gradle to use v2.11.1 causes this error to go away.

**Comment by sojanpr** [comment]
@gjsalot Sorry that you are facing this issue. We have added Firebase as an `optional dependency` in the new version of SDK in order to provide new content listing features provided by Firebase. How are you integrating the SDK to your project?  Are you adding it by compiling the  dependency
`compile ('io.branch.sdk.android:library:2.+')`

**Comment by sojanpr** [comment]
@gjsalot We have tested with the  dependency
compile 'io.branch.sdk.android:library:2.12.0' and it seems working fine. Are you using any other way to include the sdk? If not can you please check if you have any special compiler setting to check optional class reference in files?

**Comment by sojanpr** [comment]
@gjsalot It look like more to do with your proguard settings. Can you please write to our awesome integration team (integrations@branch.io) so that we can sort out this quickly.

**Comment by hobera** [comment]
@gjsalot We also encountered this error, we managed to build by adding this in our pro guard rules:

`-dontwarn io.branch.indexing.**`

@sojanpr : is there a recommended way in fixing this?

thanks

**Comment by sojanpr** [comment]
@hobera Thank you very much for updating this. We have added  some optional dependency in order  to provide better performance  by avoiding Java reflection. Unfortunately proguard check on  all class  reference and warns if it is not finding it (Even if we don't use them at runtime)

Currently if you have project specific proguard rules set, you need  to add 
`-dontwarn com.google.firebase.appindexing.**`
We will check for a better alternative and update.
Thanks

**Comment by ipereziriarte** [comment]
@sojanpr If that's the solution, you should add it to the README.md file

**Comment by sojanpr** [comment]
@ipereziriarte We are checking for any possible solution. We will definitely update the READE soon. 
Thanks for the reminder

**Comment by snijsure** [comment]
@sojanpr was readme file updated, wasted about 30 min this morning and finally adding `-dontwarn com.google.firebase.appindexing.**` fixed my compile issue, can someone update README 🙏  🙏

**Comment by EvangelosG** [comment]
@snijsure it was! https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/README.md#proguard-warning-or-errors-with-appindexing-module

**Comment by snijsure** [comment]
@EvangelosG my bad , thanks!
