### ISSUE TITLE
Not Able to Open app From facebook

### ISSUE THREAD

**Issue by charchit28** [BranchMetrics/android-branch-deep-linking#479]
If there is a bug or error in this repo, please file the issue here. 

If you need assistance integrating a Branch SDK, please email support@branch.io. Thank you.

**Comment by EvangelosG** [comment]
Hi @charchit28 -- We have an awesome support team for situations like these. Please email integrations@branch.io with an elaborated explanation (what kind of device, what link were you clicking, was it native FB or mobile FB). If this ends up being an SDK issue I'll open this back up.
