### ISSUE TITLE
on Samsung S8+ Branch take user to Playstore but doesn't work after App installed.

### ISSUE THREAD

**Issue by polenchheang** [BranchMetrics/android-branch-deep-linking#482]
Hi All,

First apology for lack of information.
The information that we got are:
1. User click on our Branch link while they don't have our App installed.
2. PlayStore is opened and User install our App then Open it
Issue: App doesn't go through the flow as if Branch link haven't clicked.
This issue happen only on Samsung Galaxy S8+
If User have installed the App, App work as expected.

Is there any Branch deeplink issue you aware of that happen specifically on Samsung Galaxy S8+?

**Comment by EvangelosG** [comment]
Hi @polenchheang -- The only Samsung specific issues we've seen involved the Samsung Messenger app, and from our testing it seems to be working correctly. Can you please send this information to integrations@branch.io ? They're a great team in the same building as myself, and they work through these issues all day for partners. If there's an SDK bug I'll make sure to open this back up and post the resolution for others.
