### ISSUE TITLE
generateShortUrl Not working 

### ISSUE THREAD

**Issue by SumitMarwha** [BranchMetrics/android-branch-deep-linking#486]
I have tested this library in lots of phone. It is working fine everywhere except Redmi Note 4. Can you share the solution for this phone. onLinkCreate function is never called in Redmi Note 4

**Comment by sojanpr** [comment]
@SumitMarwha Sorry that you are facing this issue. Could you please  send us the logs from the specific device? It look like Branch session might not have initialized on the device.

**Comment by EvangelosG** [comment]
Hi @SumitMarwha -- as we don't have access to a Redmi Note 4, if you ever loop back to this issue please enable logging (Branch.enableLogging() in your Application class before GetAutoInstance) and send us whatever Logcat spits out during this process. From there we will investigate, until then I am closing this issue.
