### ISSUE TITLE
BranchReferralInitListener:: onInitFinished not invoked upon successful initSession

### ISSUE THREAD

**Issue by mradzinski** [BranchMetrics/android-branch-deep-linking#494]
Just like the title says, at least in Kotlin BranchReferralInitListener::onInitFinished callback is not invoked upon initSession.

```kotlin

class App : MultiDexApplication() {
    override fun onCreate() {
         super.onCreate()
         Branch.getAutoInstance(this)
    }
}
```

```kotlin
    override fun onStart() {
        super.onStart()

        val branchListener = Branch.BranchReferralInitListener { referringParams, error ->
            // NOT BEING INVOKED.
        }

        if (intent.data != null) {
            Branch.getInstance().initSession(branchListener, intent.data, this)
        } else {
            //...
        }
    }
```

**Comment by mradzinski** [comment]
Upon further debugging the callback seems to end up being null inside the Branch.io SDK. At some point during the whole initialisation the callback reference seems to be GB or something like that 😕 . Any idea why this might happen?

**Comment by sojanpr** [comment]
@mradzinski looks toan issue with scope of your listener. The `val branchListener`  is defined  inside the `instant()` method and it can be GCed when `onStart()` finishes. Do you think defining this listener at class level will fix the issue?

**Comment by mradzinski** [comment]
Well, actually the `branchListener` is defined inside the scope of `onStart` so there's no way it can be GCed. However, I defining it at class level too and I get the same outcome (`initSession` receives a `null` callback paramater).

**Comment by sojanpr** [comment]
@mradzinski can you please try this below snippet. It worked fine for me
```override fun onStart() {
        super.onStart()
        Branch.getInstance().initSession({ referringParams, error ->
            Log.d("BranchTestBed", "Init session finished!")
        }, this.intent.data, this)
    }```

**Comment by mradzinski** [comment]
Tried it, "Init session finished!" is not being logged.

**Comment by sojanpr** [comment]
This is working fine always with. Is there a chance that you are finishing this activity or moving to another  activity before `initSession` called back?

**Comment by mradzinski** [comment]
Not really. Actually, my Splash activity is getting stuck due to this (I have some logic to either move to one or another activity given the deeplink properties inside the callback).

**Comment by sojanpr** [comment]
@mradzinski It look like there is some other integration issue here. Can you please write to support@branch.io We can help you better and faster there with some samples

**Comment by mradzinski** [comment]
Will do.

**Comment by blbradley** [comment]
I'm also having this issues on the React Native end of things. What was the final resolution?

**Comment by mradzinski** [comment]
@blbradley Can't really say or recommend anything mate, I'm a native developer. On this scenario it happened to be a bug on the SDK that got fixed almost immediately.

Sorry I can't be of much help. But try mailing support, they normally answer pretty fast.

Best of luck.
