### ISSUE TITLE
Not be able to read referral params when click on branch link for every time.

### ISSUE THREAD

**Issue by vijayMmenlo** [BranchMetrics/android-branch-deep-linking#496]
The latest version of Branch 2.13.0(https://github.com/BranchMetrics/android-branch-deep-linking/releases/tag/2.13.0) --- > Not working in Android. Means, Not be able to read/get any referral params once we click on email generated branch Link.

Some times able to read and some times not be able to read. I realized to fix this issue is downgrading the Branch Android SDK version to 2.12.2. Now everything is working fine.

Please fix this issue in latest version i.e., 2.13.0

**Comment by sojanpr** [comment]
@vijayMmenlo We are working on this issue. will update the SDK asap. Thanks for reaching out

**Comment by sojanpr** [comment]
@vijayMmenlo We have opened a PR #497 for this issue. Will be releasing shortly after QA pass

**Comment by sojanpr** [comment]
@vijayMmenlo  we have released v2.13.1 with the fix for this issue. Can you please try that.
