### ISSUE TITLE
Branch.io params is always empty when my app is on background (opened)

### ISSUE THREAD

**Issue by rkmax** [BranchMetrics/android-branch-deep-linking#501]
I have a pretty straight forward setting, setup

- my intent filters for my main activity on the manifest
- singleTask mode for all my activities (it just have two)

My app have two entry points: one the intent filter will call my MainActivity which start the branch session return the values on the referringParams and I go to the SecondActivity, everyone is happy

the another entry point is the launcher, when I click open the MainActivity do somethhing different because intent.data is empty and Go to SecondActivity, the problem is as follows, after the app is in the SecondActivity and the app goes background (e.g. touch home button) and then tap on some link the MainActivity is launched intent.data is not empty there's a valid url but when my callback is called I got referringParams empty `{}` or something like `{"+clicked_branch_link":false,"+is_first_session":true}` but the data that is important for me is not there

I dont know what is wrong with this. i have spend some hours without success

    @Override
    public void onStart() {
        super.onStart();
        Branch branch = Branch.getInstance();
    
        branch.initSession(new Branch.BranchReferralInitListener(){
            @Override
            public void onInitFinished(JSONObject referringParams, BranchError error) {
                if (error == null) {
                    // here referringParams is a empty {} object
                } else {
                    Log.i("MyApp", error.getMessage());
                }
            }
        }, this.getIntent().getData(), this);
    }

    @Override
    public void onNewIntent(Intent intent) {
        this.setIntent(intent);
    }

This is a copy of the question I did on SO https://stackoverflow.com/q/47166477/816721

**Comment by sojanpr** [comment]
@rkmax The integration looks correct. Can you please make sure you are using the latest version of the SDK (v2.13.1). We have fixed couple of thing on v2.13.0 which may cause the above issue.

Testing the same steps with the `TestBed` app (https://github.com/BranchMetrics/android-branch-deep-linking/tree/master/Branch-SDK-TestBed)  embdded along with the SDK seems working fine.

For a quicker response can you please write to integrations@branch.io

**Comment by rkmax** [comment]
@sojanpr the bug still is present on the version 2.13.1

**Comment by sojanpr** [comment]
@rkmax Can you please help with logs or  steps to reproduce in TestBed app. We are  unable to reproduce this issue on our side. 

For a quicker response on integration issues please write to integrations@branch.io

**Comment by EvangelosG** [comment]
@rkmax hope you got things working. If we hear from you we'll open this back up.

**Comment by rkmax** [comment]
Sorry my inactivity, @EvangelosG  @sojanpr I put this at the bottom of my priorities right now, I did some testing a simple code like the testbed I was not able to reproduce. that makes me wander is the way my app with the problem was built. when I can take this problem Possible I'll put here some thoughts of the problem

**Comment by EvangelosG** [comment]
👍

**Comment by SkilyFrance** [comment]
Hello,
I have implemented the branch.io 's Flutter SDK in my production app. 

Works fine on iOS (Debug/Prod) and only in Android (Debug). 
My issue is about the Android Playstore version : When my app is in background , and I click on the Deeplink, the app opens successfully but receives an empty data from the link.

The background state works fine on debug but not on production (Playstore).

I have added the SHA256, from PlayStore on AppLinks Cert Fingerprints, and check my AndroidManifest but no fix seems to work. 

Could you help me to find a way to fix it ? 

Best regards, 
Guillaume

**Comment by vqthanh1412489** [comment]
> Hello, I have implemented the branch.io 's Flutter SDK in my production app.
> 
> Works fine on iOS (Debug/Prod) and only in Android (Debug). My issue is about the Android Playstore version : When my app is in background , and I click on the Deeplink, the app opens successfully but receives an empty data from the link.
> 
> The background state works fine on debug but not on production (Playstore).
> 
> I have added the SHA256, from PlayStore on AppLinks Cert Fingerprints, and check my AndroidManifest but no fix seems to work.
> 
> Could you help me to find a way to fix it ?
> 
> Best regards, Guillaume

The same issue. Do you resolve it?
