### ISSUE TITLE
Intent filter should not mention android:host="open" in README

### ISSUE THREAD

**Issue by efung** [BranchMetrics/android-branch-deep-linking#505]
The intent-filter example in the README mentions this:

`        <data android:scheme="yourapp" android:host="open" />`

However, I believe only the `scheme` is required, and the `host` part should be removed.

**Comment by sojanpr** [comment]
@efung, This is for the URI scheme based deep linking. `host` helps when there is multiple activities with one URI scheme (Similar to `pathPrefix`  while using app links). The defult host for Branch link is `open`

**Comment by vkotovv** [comment]
Did not work for me without `android:host="open" ` using `io.branch.sdk.android:library:3.2.0`. However, the docs [here](https://docs.branch.io/apps/android/) do not mention it.
