### ISSUE TITLE
addcontentmetadata is deprecated

### ISSUE THREAD

**Issue by ChiHwe** [BranchMetrics/android-branch-deep-linking#507]
Hi , 
i facing the addcontentmetadata is deprecated issue: 
BranchUniversalObject branchUniversalObject = new BranchUniversalObject()
                        .setCanonicalIdentifier(Canonical)
                        .setCanonicalUrl(Canonical_url)
                        .setTitle(tv_sub_selling_title.getText().toString())
                        .setContentDescription(tv_sub_selling_description.getText().toString().replaceAll("\r\n", ""))
                        .setContentImageUrl(photo_seleted.get(0))
                        .setContentIndexingMode(BranchUniversalObject.CONTENT_INDEX_MODE.PUBLIC)
                        .addContentMetadata("action","goJob")
                        .addContentMetadata("job_id", job_id_public);

these 2 values(addcontentmetadata)  are unable to added to the BUO, please kindly advice. 
previously no issue, this issue happen today.

**Comment by ChiHwe** [comment]
I found a solution for above problem. For those who integrate facing this problem, please use setContentmetadata. 
first  declare :

 ContentMetadata contentMetadata = new ContentMetadata();

then add: 
contentMetadata.addCustomMetadata("action","goTheme");
contentMetadata.addCustomMetadata("theme_id", getIntent().getStringExtra("theme_id"));

then last: 
BranchUniversalObject branchUniversalObject = new BranchUniversalObject()
                        .setContentMetadata(contentMetadata);

**Comment by EvangelosG** [comment]
Hi @ChiHwe -- we'll be updating docs to reflect this change ASAP, thank you for bringing to my attention.
