### ISSUE TITLE
facebook-Deeplinking by branch.io triggers alert message

### ISSUE THREAD

**Issue by FelixMobile** [BranchMetrics/android-branch-deep-linking#509]
We are at the end of the devolpment of an app. 
Everyhting has worked fine untill we have used an deep-link in facebook that is provided by branch.io.
If we use this deep-link we get the attached alert-message. In addition to that: As soon the alert-message appears other  functions of the app are negative effected as well.
![ohne titel](https://user-images.githubusercontent.com/34035507/33276607-5167326c-d396-11e7-92b0-7adf03416530.png)

Is there anybody who can help?
I would really appreciated.
(we are working with react-native)

![ohne titel](https://user-images.githubusercontent.com/34035507/33276677-8292a326-d396-11e7-849f-86514ed3a859.jpg)
If you need assistance integrating a Branch SDK, please email support@branch.io. Thank you.

**Comment by EvangelosG** [comment]
Hi @FelixMobile -- thanks for bringing this React Native implementation issue to our attention. Please contact integrations@branch.io with the information you provided and our wonderful support team will take a look ASAP. If there's an issue relating to the native Android SDK I'll loop back here to comment.
