### ISSUE TITLE
Adding more details to releases ?

### ISSUE THREAD

**Issue by salah-ghanim** [BranchMetrics/android-branch-deep-linking#515]
I'm trying to maintain branch sdk in our project, and without having a good reason to update I usually avoid updates and I think this is a very common practice in android.

so adding details to the release can help us decide to update or wait for the next release

**Comment by sojanpr** [comment]
@salah-ghanim we have a change log file with our repo for tracking changes for each realease. 
Here is the link to it 
https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/ChangeLog.md
Do you think this can help

**Comment by salah-ghanim** [comment]
it does help, thanks for the info.
but also github has a release note / message that can help too :)
