### ISSUE TITLE
Android : Deep Link navigation clearing the previous activities from the stack.

### ISSUE THREAD

**Issue by vijayMmenlo** [BranchMetrics/android-branch-deep-linking#516]
Hi Team,

Android Deep linking works with SingleTask as launch mode. But if we use this launch mode, it clears previous activities as explained in below example.
Ex: Imagine there are 3 activities A, B & C.
     A ->B ->C ->Home -> A (Not showing C) - Clearing B,C activites
     A ->B ->C -> Home -> C (**Expected Behavior**)
With SignleTask, not be able to achieve **expected behavior**. Other than this launch modes, Application has come up with multiple instances and other issues.
FYI: Sample example     --   http://imgbin.org/images/15515.gif

How should I work with SingleTask with preserving previous activities and is it necessary to use SingleTask with branch?

Regards,
Vijay

**Comment by sojanpr** [comment]
@vijayMmenlo  Branch  doesn't need `SingleTask` mode for its operation but unfortunately Android  opens a new instance of the app if you don't have `SingleTask` mode to your deep linking activity.
(Also you may find  others issues if you are not setting `SingleTask` mode, e.g. app appears like opened inside the app from which the link clicked  )

One option is to move your deep linking code  to an activity that is not filtering the deep link schemes. This way you can maintain the state of the Activity stack when launched from background.
In your case can you handle deep link in any other activity  than `A`?

**Comment by sojanpr** [comment]
@vijayMmenlo did the above help to solve the issue? For quicker response on integration issues can you please write to our awesome integration team integrations @branch.io
