### ISSUE TITLE
ConcurrentModificationException in ServerRequestQueue

### ISSUE THREAD

**Issue by dmkessler** [BranchMetrics/android-branch-deep-linking#521]
There is a ConcurrentModificationException in this class due to improper synchronization usage,  spawning new threads to run operations on a list, and using a for-each loop instead of an iterator.  The log is truncated but I can try to provide something more inclusive if necessary.  I have the fix locally but I can't push to a branch to create a pull request due to permissions.

As reported by Crashlytics:  
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.LinkedList$LinkIterator.next(LinkedList.java:124)
       at io.branch.referral.ServerRequestQueue$1.run(ServerRequestQueue.java:70)
       at java.lang.Thread.run(Thread.java:841)

**Comment by sojanpr** [comment]
@dmkessler Thanks for the report. We have added a temporary fix to the problem in v2.14.3.
Can you please  use this version. 
Here is the PR we added to fix the issue https://github.com/BranchMetrics/android-branch-deep-linking/pull/520

**Comment by dmkessler** [comment]
@sojanpr I saw the temporary fix.  Thank you for fixing that so quickly for us.  I have created a PR that should address the issue in a more permanent solution located here: https://github.com/BranchMetrics/android-branch-deep-linking/pull/522

**Comment by sojanpr** [comment]
Added a fix and released with v2.14.4 @dmkessler  thanks  for your help
