### ISSUE TITLE
Tracking User Actions and Events issue

### ISSUE THREAD

**Issue by ChiHwe** [BranchMetrics/android-branch-deep-linking#523]
Hi Branch support, 

We facing some problem on android and IOS integration , 

we want to using the "Branchevent" to tracking the user Actions and events, 

we using the below coding: 

new BranchEvent(BRANCH_STANDARD_EVENT.PURCHASE)
    .setAffiliation("affiliation_value")
    .setCoupon("coupon_value")
    .setCurrency(CurrencyType.USD)
    .setTax(12.3)
    .setRevenue(1.5)
    .setDescription("Event_description")
    .setSearchQuery("related_search_query")
    .addCustomDataProperty("Custom_Event_Property_Key", "Custom_Event_Property_Val")
    .addContentItems(contentBUO1, contentBUO2)
    .logEvent(context);

new BranchEvent("My_Custom_Event")
    .addCustomDataProperty("key1", "value1")
    .addCustomDataProperty("key2", "value2")
    .logEvent(context);

to track the user action, but the action did not log to the LiveView in the branch dashboard; 

only the this is working: 
   HashMap<String, String> hashmap_action = new HashMap<>();
            hashmap_action.put("seller_id", seller_id);

            branchUniversalObject.userCompletedAction("shop_share",hashmap_action);

However this one: userCompletedAction is deprecated in IOS , so it has some problem between IOS and android, please kindly advice. thanks. 
thanks.

**Comment by sojanpr** [comment]
@ChiHwe  Thanks for reaching out. 
Currently the new Branch events are showing under cross-channel-analytics/source in your Branch dashboard.  We will soon add support to these events to  `Live View`.

**Comment by ChiHwe** [comment]
Hi sojanpr, may i know when will the events go live to List View ?

**Comment by sojanpr** [comment]
@ChiHwe Sorry for the inconvenience. We are still working on this. Will update you once it is relased.
