### ISSUE TITLE
How to update the message body according to selected app upon sharing

### ISSUE THREAD

**Issue by henrytang-gbb** [BranchMetrics/android-branch-deep-linking#530]
Hi, 

As mentioned, how should I (can I) update the message body for a particular app, say, Facebook/ Whatsapp?

I have read the documentations for both iOS and Android,
it seems there is a BranchShareLink class for which can update the shareText by channel making use of the BranchShareLinkDelegate.

But I don't find any solution for Android side...
The closest one is the BranchUniversalObject.showShareSheet()
with the onChannelSelected() listener
Yet, the message body is set upon calling showShareSheet() and seems cannot be modified afterwards...

Any clue? Or did I overlook something?

Thanks for any help!!!

**Comment by sojanpr** [comment]
@henrytang-gbb Android SDK has no feature to change the deep link data on channel selected event. (SDK internally set the the channel name to the selected channel though). We are working on this and add this feature soon. Keep you updated

**Comment by sojanpr** [comment]
@henrytang-gbb  We have added  this feature from v2.14.5 .Please use `ExtentedBranchLinkShareListner` for modifying the  link params after selecting  a channel. An  example is here 
 https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/Branch-SDK-TestBed/src/io/branch/branchandroiddemo/MainActivity.java#L306
