### ISSUE TITLE
Second click on Branch link issue (2.14.4)

### ISSUE THREAD

**Issue by edinaleitner** [BranchMetrics/android-branch-deep-linking#532]
First time i click on a branch link, everything is ok, i have all the data, and the 'clicked_branch_link' attribute is 'true'.
After that, I kill the app (not sure if it is a mandatory step), and click on the same branch link again -> i have no data, and 'clicked_branch_link' attribute is 'false'. This issue persist until i Clear Data from Settings.

Reverted to 2.11.0, the issue is not happening in that version.

**Comment by sojanpr** [comment]
@edinaleitner Sorry for this issue. We had a bug related to  device orientation changes that can trigger the same issue. It got fixed in 2.14.4 . Can you please try this version.

**Comment by edinaleitner** [comment]
Hello Sojan, as the title of this issue says, the bug happens in lib version 2.14.4.

**Comment by sojanpr** [comment]
@edinaleitner @cesarsicas  Sorry for the issue. We are trying to reproduce the issue and fix it.
Can you please help by trying the following 
1) Run TestBed app in this repo on the device you see the issue  and see if you can reproduce
2) Can you please try if adding following snippet to you `Application#onCreate()` method helps
```@Override
    public void onCreate() {
        super.onCreate();
        Branch.disableInstantDeepLinking(true);
    }```

**Comment by sojanpr** [comment]
We have added a fix for not getting data when app is opened from back ground here https://github.com/BranchMetrics/android-branch-deep-linking/pull/533
Will be added  to next release

**Comment by cesarsicas** [comment]
@sojanpr I coudn't install TestBed, the apk seems corrupted. But i tried include the line  Branch.disableInstantDeepLinking(true) and worked ! Thanks !

I could test just in one device (LG K10 LTE / Android 6.0) for a while.

**Comment by sojanpr** [comment]
@cesarsicas Thank you very much. We will check why this happened on that particular device and add more generic fix.

**Comment by sojanpr** [comment]
@edinaleitner did the above help you as well ?

**Comment by edinaleitner** [comment]
the workaround proposed by you works (Branch.disableInstantDeepLinking(true)).
but in v2.14.5 the issue is still not fixed, as you said above.

**Comment by sojanpr** [comment]
@edinaleitner  We have added new feature called  Instant Deep linking from 2.14.0 in order to speed up the overall deep link process (by avoiding network latencies as much as possible). This is an additional feature which is not affecting any of the existing Branch features. So turning it off using above method will not affect any of normal functions. We are still checking why this is happening  in some cases and will fix it soon . Until then please feel confident to use the above work around.

**Comment by nsekhar90** [comment]
I was facing the same issue and the above work around works fine for now. Thanks
