### ISSUE TITLE
Starting an offline app - initSession never returns 

### ISSUE THREAD

**Issue by edinaleitner** [BranchMetrics/android-branch-deep-linking#534]
Hello, we have found another issue:
- clear data from Settings
- if the app is started without an active internet connection, branch.initSession -> onInitFinished will never be fired. we've waited for the response for several minutes, much more than the network timeout value (3000ms).

- everything is set-up as in the docs. we call Branch.getAutoInstance in Application class's onCreate. In the launcher activity we call Branch.getInstance().initSession...

- i think the issue is if in Application.onCreate we call Branch.getAutoInstance(...) without internet connection.

**Comment by sojanpr** [comment]
@edinaleitner We have fixed this issue in v2.14.5. Can you please try this version
