### ISSUE TITLE
Cannot build apk with minifyEnable=true on v2.14.5

### ISSUE THREAD

**Issue by edinaleitner** [BranchMetrics/android-branch-deep-linking#535]
I updated the library from 2.14.4 to 2.14.5.
Build apk is not working (./gradlew assembleDebug from terminal), if minifyEnabled is set to TRUE.
This worked in the previous version (2.14.4)
It works if i set minifyEnabled to FALSE.

**Comment by sojanpr** [comment]
@edinaleitner There is nothing changed in SDK  pro-guard settings from 2.14.4 to  2.14.5. We are able to build  apk  after enabling `minify`. Can you please check if there any thing changed with your proguard rules. If you still have the issue could you please update the error message.

**Comment by edinaleitner** [comment]
@sojanpr there is nothing changed in our proguard rules.
The only change is:   
BEFORE -> compile 'io.branch.sdk.android:library:2.14.4'     
AFTER -> compile 'io.branch.sdk.android:library:2.14.5'

Before the gradle build was successful, after we have the following errors:

20:34:05.049 [ERROR] [system.err] Warning: there were 30 unresolved references to classes or interfaces.
20:34:05.049 [ERROR] [system.err]          You may need to add missing library jars or update their versions.
20:34:05.049 [ERROR] [system.err]          If your code works fine without the missing classes, you can suppress
20:34:05.049 [ERROR] [system.err]          the warnings with '-dontwarn' options.
20:34:05.049 [ERROR] [system.err]          (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
20:34:05.049 [QUIET] [system.out] Warning: Exception while processing task java.io.IOException: Please correct the above warnings first.

**Comment by sojanpr** [comment]
@edinaleitner Unfortunately the above error logs does not say which class is missing. Do you see any more details on this error?
Can you please make sure you have all the `-dontwarn` added to your proguard mentioned here
https://github.com/BranchMetrics/android-branch-deep-linking#troubleshooting

**Comment by edinaleitner** [comment]
@sojanpr yeah, that was it, i had to add the -dontwarn lines, and not it works!
Don't know why this wasn't an issue until this version.
(maybe you should put this in the documentation on the website)

thank you!

**Comment by sojanpr** [comment]
@edinaleitner Glad it worked , we have it already in the  integration guide but will make sure it is updated  in all docs
