### ISSUE TITLE
Deep link is not working with release apk

### ISSUE THREAD

**Issue by pdubeypublic571** [BranchMetrics/android-branch-deep-linking#541]
Deep link  is not working with release apk. I configured every thing before 2hrs. Tell me how much time google takes to add in **DAL**.  

Error: Always throwing to playstore whether app is installed or not.

**Comment by sojanpr** [comment]
@pdubeypublic571 "Always throwing to playstore whether app is installed or not" seems like not an issue with DAL. DAL comes into picture only for auto verification of your app links.
Can you please check following things done  correctly
1) Did you have the correct package name on Branch Dash board
2) Do you have URI scheme added  in the Branch Dash board  and your main activity filtering for the  same.
3) Can you please share the link you are trying if any of the above is not helpful

for a quick response on integration issue can you please contact our intergration support team at integrations@branch.io

**Comment by sojanpr** [comment]
@pdubeypublic571  Did the above help? Do you still face any issue?

**Comment by pdubeypublic571** [comment]
I have configured every thing with perfection. But still getting issues in release apk. If i am gonna debug it then it works fine in debug mode and installing a signed apk then it always throwing to play store not to application.

**Comment by sojanpr** [comment]
@pdubeypublic571 We couldn't reproduce this issue. Could you please reach out to our awesome  integration  team integrations@branch.io to get a faster support on integration issues

**Comment by heena-viprak** [comment]
Hello,
we are also facing the same issue that when we generate release APK and click on the branch.io deeplink(Generated using REST API) then link always falls back to playstore.
When we use debug.APK then deeplink is opening our app perfectly.

 Can you please provide solution to it.
Thank you.

**Comment by kikre445** [comment]
Estoy de acuerdo a eso
