### ISSUE TITLE
Incompatibility with Auth0 accounts connection

### ISSUE THREAD

**Issue by endy-s** [BranchMetrics/android-branch-deep-linking#542]
Hello there!

I'm developing a Deep Link using Branch IO, and in the application I also perform authentication using Auth0, and this includes the connection with the user's LinkedIn account.

There was no problem during the development of the DeepLink for the Android app.

Unfortunately, I'm having some issues in the iOS app. If I try to use the `initSession` method, the requests to connect with the user's LinkedIn account fails. 

When I try to connect with LinkedIn account, the webview is suddenly finished and this is only console output I receive :
`params @: ["+clicked_branch_link": 0, "+is_first_session": 0]`

This is the AppDelegate's code related to BranchIO and Auth0:
``` swift
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        ...
        getBranchIOInfo(launchOptions: options)        
        ...        
        return true
    }
            

func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey: Any] = [:]) -> Bool {
        if url.absoluteString.starts(with: "myapplink") {
            DeepLinkHelper.shared.currentDeepLink = DeepLink()

            guard let rootViewController = window?.rootViewController, let loading = UIStoryboard(name: "Main", bundle: nil).instantiateInitialViewController() else { return false }

            if let snapshot = loading.view.snapshotView(afterScreenUpdates: true) {
                rootViewController.view.addSubview(snapshot)
                snapshot.layer.opacity = 0
                UIView.animate(withDuration: 0.3, animations: {
                    snapshot.layer.opacity = 1
                }, completion: { _ in
                    snapshot.removeFromSuperview()
                    self.window?.rootViewController = loading
                    self.window?.makeKeyAndVisible()
                })
            }

            return true
        } else {
            return Auth0.resumeAuth(url, options: options)
        }

    }


func getBranchIOInfo(launchOptions: [AnyHashable: Any]?) {
        // TODO: Remove configuration to use Test Key before releasing to Production
        Branch.setUseTestBranchKey(true)
        let branch: Branch = Branch.getInstance()
        branch.initSession(launchOptions: launchOptions, andRegisterDeepLinkHandler: {params, error in
            if error == nil {
                guard let data = params as? [String: AnyObject], let deepLinkInfo = DeepLink(JSON: data) else { return }
                
                print("params @: \(data)")
                
                if deepLinkInfo.linkType != .unknown {
                    DeepLinkHelper.shared.currentDeepLink = deepLinkInfo
                }
                DeepLinkHelper.shared.processDeepLink {
                    self.setupRootModule()
                    self.presentInitialScreen()
                }
            }
            branch.resetUserSession()
        })

    }
```

I already tried the other [options from the documentation](https://docs.branch.io/pages/apps/ios/#read-deep-link), and the closer option was the `getLatestReferringParams`,  but, as documentation says, it gets the previous session info...
I also tried the `getLatestReferringParamsSynchronous` but it never returned...

Can you please help me with this out? 

Thanks!

**Comment by E-B-Smith** [comment]
Check that `data["+clicked_branch_link"]` is `true` to make sure that it's a Branch link before handling it, else pass the link to the login auth handler.

Also, look at the Branch iOS SDK GitHub which has iOS specific answers, examples and is a better to ask questions.

https://github.com/BranchMetrics/ios-branch-deep-linking

Here's a rough example:

```
func getBranchIOInfo(launchOptions: [AnyHashable: Any]?) {
    // TODO: Remove configuration to use Test Key before releasing to Production
    Branch.setUseTestBranchKey(true)
    let branch: Branch = Branch.getInstance()
    branch.initSession(launchOptions: launchOptions, andRegisterDeepLinkHandler: {params, error in
        if error !=  nil {
            print("Deep link error: \(error)")
            return
        }
        print("params @: \(data)")
        if let data = params as? [String: AnyObject],
           let deepLinkInfo = DeepLink(JSON: data),
           let bool: isBranchLink = data["+clicked_branch_link"] {
           if isBranchLink {
              // It's a Branch link! Handle it:
              DoBranchDeepLinkStuff(deepLinkInfo)
           } else {
              // Do the rest of auth or whatever here:
           }
        }
    })
}
```

**Comment by endy-s** [comment]
Thanks for the quick answer!
I only can test it again in Monday, but I believe that your example will help a lot!

Sorry for posting it in the android repo, got confused working in both platforms and didn't notice that was posting in the wrong repo.

Thanks again!

**Comment by endy-s** [comment]
Hey @E-B-Smith 

Got it to work! 
I added the `isBranchLink` check that you suggested. 
Couldn't perform the Auth0 logics on the Branch callback because I need the URL, but it is working as expected in the application with URL delegate.

Thank you very much!
