### ISSUE TITLE
Compile error with branch library version 2.15.0   

### ISSUE THREAD

**Issue by chinloong** [BranchMetrics/android-branch-deep-linking#543]
I am getting the errors below when compiling release apk with Proguard enabled with current branch library version 2.15.0. I don't get error when I revert back to branch library version 2.14.5 

Information:Gradle tasks [:app:assembleReleaseProd]
Warning:io.branch.referral.InstallListener$ReferrerClientWrapper$1: can't find superclass or interface com.android.installreferrer.api.InstallReferrerStateListener
Warning:io.branch.referral.InstallListener$ReferrerClientWrapper: can't find referenced class com.android.installreferrer.api.InstallReferrerClient
Warning:io.branch.referral.InstallListener$ReferrerClientWrapper: can't find referenced class com.android.installreferrer.api.InstallReferrerClient$Builder
Warning:io.branch.referral.InstallListener$ReferrerClientWrapper: can't find referenced class com.android.installreferrer.api.InstallReferrerClient
Warning:io.branch.referral.InstallListener$ReferrerClientWrapper: can't find referenced class com.android.installreferrer.api.InstallReferrerClient$Builder
Warning:io.branch.referral.InstallListener$ReferrerClientWrapper: can't find referenced class com.android.installreferrer.api.InstallReferrerClient
Warning:io.branch.referral.InstallListener$ReferrerClientWrapper$1: can't find referenced class com.android.installreferrer.api.InstallReferrerClient
Warning:io.branch.referral.InstallListener$ReferrerClientWrapper$1: can't find referenced class com.android.installreferrer.api.ReferrerDetails
Warning:io.branch.referral.InstallListener$ReferrerClientWrapper$1: can't find referenced class com.android.installreferrer.api.InstallReferrerStateListener
Warning:io.branch.referral.InstallListener$ReferrerClientWrapper$1: can't find referenced class com.android.installreferrer.api.ReferrerDetails

**Comment by sojanpr** [comment]
@chinloong We have added an optional dependency on Google Install Referrer lib with v2.15.0 for better install tracking. Can you please add the `-dontwarn com.android.installreferrer.api.**` to your proguard rules to remove the warnings.

We have updated the documentation here
https://github.com/BranchMetrics/android-branch-deep-linking#proguard-warning-or-errors-with-appindexing-module

**Comment by chinloong** [comment]
@sojanpr Thanks! It's working now.

**Comment by sojanpr** [comment]
@bricestacey  Thanks for the note. Will update this soon. 
We have it in the in the SDK documentation here
https://github.com/BranchMetrics/android-branch-deep-linking#proguard-warning-or-errors-with-appindexing-module
