### ISSUE TITLE
Proguard issues in v2.15

### ISSUE THREAD

**Issue by josalvdel1** [BranchMetrics/android-branch-deep-linking#545]
Hey guys, after update from 2.14.+ to 2.+, I'm getting the following errors trying to compile my project with proguard:

`Warning:io.branch.referral.InstallListener$ReferrerClientWrapper$1: can't find superclass or interface com.android.installreferrer.api.InstallReferrerStateListener
Warning:io.branch.referral.InstallListener$ReferrerClientWrapper: can't find referenced class com.android.installreferrer.api.InstallReferrerClient$Builder
Warning:io.branch.referral.InstallListener$ReferrerClientWrapper: can't find referenced class com.android.installreferrer.api.InstallReferrerClient
Warning:io.branch.referral.InstallListener$ReferrerClientWrapper: can't find referenced class com.android.installreferrer.api.InstallReferrerClient$Builder
Warning:io.branch.referral.InstallListener$ReferrerClientWrapper: can't find referenced class com.android.installreferrer.api.InstallReferrerClient
Warning:io.branch.referral.InstallListener$ReferrerClientWrapper$1: can't find referenced class com.android.installreferrer.api.InstallReferrerStateListener
Warning:io.branch.referral.InstallListener$ReferrerClientWrapper$1: can't find referenced class com.android.installreferrer.api.InstallReferrerClient
Warning:io.branch.referral.InstallListener$ReferrerClientWrapper$1: can't find referenced class com.android.installreferrer.api.ReferrerDetails
Warning:there were 15 unresolved references to classes or interfaces.
Warning:Exception while processing task java.io.IOException: Please correct the above warnings first.`

Can you confirm? 
Regards.

**Comment by sojanpr** [comment]
@josalvdel1 We have added an optional dependency on Google Install Referrer lib with v2.15.0 for better install tracking. Can you please add the -dontwarn com.android.installreferrer.api.** to your proguard rules to remove the warnings.

We have updated the documentation here
https://github.com/BranchMetrics/android-branch-deep-linking#proguard-warning-or-errors-with-appindexing-module
