### ISSUE TITLE
Remove redundant @nullCheck from Branch.initSession()

### ISSUE THREAD

**Issue by feresr** [BranchMetrics/android-branch-deep-linking#550]
All `initSession` method overloads have a @notNull annotation on the URI parameter. Leaving it up to the developer to perform the following null check:

```
        if (uri != null) {
          Branch.initSession(initListener, uri, activity)
        } else {
          Branch.initSession(initListener, activity)
        }
```
I wonder what's the reasoning behind this, can't branch do this check inside the `initSession(initListener, uri, activity)` ?

**Comment by sojanpr** [comment]
@feresr  Thanks for pointing this out. We already check for null internally and agree that the annotation is not needed here. Will update this with the  next version of SDK. Mean time do you think you can skip the annotation warning

**Comment by sojanpr** [comment]
@feresr  Removed the unnecessary annotations in the PR https://github.com/BranchMetrics/android-branch-deep-linking/pull/553. Will be added to the next release.
