### ISSUE TITLE
Allow developers to disable debug and info logging on test mode

### ISSUE THREAD

**Issue by lolsheeplol** [BranchMetrics/android-branch-deep-linking#551]
I'd like to have the ability to disable info logging from the BranchSdk when test mode is enabled.  Currently when a test key is used or enableTestMode is used, enabling to disabling logging does not affect the output.

I believe the logs are all coming from `PrefHelper.log` and `PrefHelper.Debug`

```
public void log(final String tag, final String message) {
        if (BNC_Dev_Debug || BNC_Logging) {
            Log.i(tag, message);
        }
    }

public static void Debug(String tag, String message) {
        if (prefHelper_ != null) {
            prefHelper_.log(tag, message);
        } else {
            if (BNC_Dev_Debug || BNC_Logging) {
                Log.i(tag, message);
            }
        }
    }
```

When `BNC_Dev_Debug` is true, logging will always happen regardless of the value of `BNC_Logging`.

**Comment by sojanpr** [comment]
@lolsheeplol Thanks for mentioning this issue. Currently SDK is logging enabled when using the test key. Will extend the meaning of `disableLogging()` to handle this case in the  coming versions.

For now the following will disable the logging even if you are using test key. Incase you want to hav this feature with current  SDK
```try {
            Field externalDebug = PrefHelper.class.getDeclaredField("BNC_Dev_Debug");
            externalDebug.setAccessible(true);
            externalDebug.setBoolean(f1,false);
        } catch (Exception ignore) {
        }```

**Comment by sojanpr** [comment]
@lolsheeplol Update this fix on this PR https://github.com/BranchMetrics/android-branch-deep-linking/pull/554 
Appreciate a review

**Comment by lolsheeplol** [comment]
@sojanpr Looks good to me.  Thank you for addressing this so quickly!
