### ISSUE TITLE
VERY strange issue with builds from GooglePlayStore

### ISSUE THREAD

**Issue by edinaleitner** [BranchMetrics/android-branch-deep-linking#558]
Hello guys, we found a very strange issue today, maybe you know something about it:
In our app we file a Branch request (initSession) at the startup of the app.

If we install the APK from command line/androidStudio everything is normal, initSession responds always.
If we install the app from Google Play Store (beta channel) the FIRST branch request - initSession responds in 20-40 seconds with an error. Retrying the request for the second time it works.

The only difference is that the build is taken from GooglePlayStore.

**Comment by sojanpr** [comment]
@edinaleitner This looks really weird. Only delay SDK has before initializing is on Goole play store referrer but this case is same irrespective the app is installed from play store or not.  Do you think your app is doing any high volume network traffic when installed from play store?

Could you please enable logging (Branch#enableLogging()) and update the logs?

For a quicker response on integration issues please write to integraions@branch.io

For a quicker response on integration issues please write to integraions@branch.io

**Comment by edinaleitner** [comment]
Further info: If the build is installed from Play Store and ran for the first time, there is no request to https://api.branch.io/v1/install
But when the same build is installed from the PC, that request is made.

**Comment by edinaleitner** [comment]
this issue was fixed with v2.15.1 Hot fix : Install requests getting stuck in the request queue if failed once. Caused by improper install referrer wait lock addition to install request.

**Comment by sojanpr** [comment]
@edinaleitner Thanks for testing it with the updated version. Since it is working now do you think we can close this issue?

**Comment by edinaleitner** [comment]
yes, you can close it.
