### ISSUE TITLE
Possible to parse a link's data without launching the Activity again?

### ISSUE THREAD

**Issue by mlostekk** [BranchMetrics/android-branch-deep-linking#559]
Is there a way to retrieve the link information without restarting the activity again? Just think of the usecase of a QRcode scanned within the application.

It is really strange to scan the qr code within the app and then ask the user wich app he wants to use to open that link.

Is there a simple way to parse an Uri and get the BranchUniversalObject information? (public boolean initSession(BranchUniversalReferralInitListener callback, @NonNull Uri data) does not work)

**Comment by sojanpr** [comment]
@mlostekk This is solved here https://github.com/BranchMetrics/android-branch-deep-linking/issues/241#issuecomment-373474848
