### ISSUE TITLE
Not possible to specify custom theme for share sheet dialog.

### ISSUE THREAD

**Issue by sttimchenko** [BranchMetrics/android-branch-deep-linking#563]
In current implementation it's not possible to specify customized dialog theme for the share sheet dialog
However, `AnimatedDialog` has a constructor that takes a `theme` as a parameter so it seems that support of the custom themes is expected, but not implemented for some reason. 

PR: [#564](https://github.com/BranchMetrics/android-branch-deep-linking/pull/564)

**Comment by sojanpr** [comment]
Thanks for the PR . Review and update with the next revision.

**Comment by sojanpr** [comment]
Fix moved to this PR https://github.com/BranchMetrics/android-branch-deep-linking/issues/565.
Will be available with next SDK version
