### ISSUE TITLE
Deep-link through Oculus Store

### ISSUE THREAD

**Issue by wpinaud** [BranchMetrics/android-branch-deep-linking#567]
It seems like the Branch.io Android SDK doesn't support deep-linking through the Oculus Store as it does for the Play store.

**Comment by wpinaud** [comment]
Thank you @sojanpr ! Do you have any idea where in your roadmap this is planned? I'm asking because this will impact our release schedule as well 🙂

**Comment by Sarkar** [comment]
@wpinaud, I don't think we have concrete plans until after Q2 of next year. I'll close this down, but I'll say that its definitely in the roadmap! Thank you for the input.
