### ISSUE TITLE
referringParams no Params

### ISSUE THREAD

**Issue by FussenYu** [BranchMetrics/android-branch-deep-linking#574]
code: 

 Branch.getInstance().initSession((referringParams, error) -> {
            if (error == null) {

                LogUtils.w("BRANCH initSession :{}", referringParams.toString());
                getReferringParams(splashCache);

            } else {
                LogUtils.e("BRANCH initSession :{}", error.getMessage());
            }
        }, intent.getData(), activity);.

always Print log 

log:

05-07 19:30:55.588 26289-26408/com.tanbeixiong.tbx_android:core I/BranchSDK: returned {"session_id":"521999711037674178","identity_id":"521999711037926236","link":"https://tbx.test-app.link?%24identity_id=521999711037926236","data":"{\"+match_guaranteed\":false,\"uid\":95420598,\"~creation_source\":0,\"+clicked_branch_link\":true,\"+click_timestamp\":1525692617,\"$one_time_use\":false,\"~id\":\"520909925577376809\",\"+is_first_session\":true,\"~referring_link\":\"https://tbx.test-app.link/52t6gw5VDM?from=singlemessage\",\"~channel\":\"tbx\",\"from\":\"singlemessage\",\"platform\":\"wx\"}","device_fingerprint_id":"521999710874281461"}
05-07 19:30:55.785 26046-26411/com.tanbeixiong.tbx_android I/BranchSDK: returned {"session_id":"521999711809613601","identity_id":"521999711767566438","link":"https://tbx.test-app.link?%24identity_id=521999711767566438","data":"{\"+clicked_branch_link\":false,\"+is_first_session\":true}","device_fingerprint_id":"521999711755284657"}

but sometimes print only:

05-07 19:30:56.017 26046-26046/com.tanbeixiong.tbx_android W/tbx_android: 05-07 19:30:56.017 pid=26046 tid=26046 <BranchUtils: lambda$initSession$0$BranchUtils: 32> BRANCH initSession :{"+clicked_branch_link":false,"+is_first_session":true}

what happened?

**Comment by sojanpr** [comment]
@FussenYu Thanks for reaching out. Looks like the issue you are pointing out is `session_id`,`identity_id` & `link` is not shown in the response. If so, this is not an issue. SDK has a logic to do `instant_deep_linking` under certain conditions with out waiting for a network operation. This is a feature added to speed up the deep link process whenever possible.

`session_id`,`identity_id` & `link` are only for Branch use and they are captured separately in case of instant deep linking.
