### ISSUE TITLE
Branch initialize at Service

### ISSUE THREAD

**Issue by hasan5151** [BranchMetrics/android-branch-deep-linking#575]
`public class MainActivity extends Service{

  
   @Override
    public void onCreate() {
        super.onCreate();

         Branch.getInstance().initSession(new Branch.BranchReferralInitListener() {
            @Override
            public void onInitFinished(JSONObject referringParams, BranchError error) {
                if (error == null) {
                    Log.i("BRANCH SDK", referringParams.toString());
                } else {
                    Log.i("BRANCH SDK", error.getMessage());
                }
            }
        }, this.getIntent().getData(), this);
    }`

How can i use Branch at Service.

**Comment by sojanpr** [comment]
@hasan5151 We are looking at a way to work it with service. Update you asap

**Comment by sojanpr** [comment]
@hasan5151 Branch Android SDK follows the Activity lifecycle for starting session and getting referral params. For your use case to get deep link params inside a service I would suggest to use Branch open API to get the deep link data from your service as described herehttps://github.com/BranchMetrics/branch-deep-linking-public-api#viewing-state-of-existing-deep-linking-urls
