### ISSUE TITLE
Call branchUniversalObject.listOnGoogleSearch() blocks the main thread for 300-800ms

### ISSUE THREAD

**Issue by AndrazP** [BranchMetrics/android-branch-deep-linking#577]
After Branch SDK integration I noticed that starting activities became slow.
Method profiling showed that branchUniversalObject.listOnGoogleSearch(); blocks the main thread for 300-800ms.
Digging deeper in your SDK source code I found our [that this method](https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/Branch-SDK/src/io/branch/indexing/AppIndexingHelper.java) is already creating a new thread for execution, but looks like [run() instead of start()](https://stackoverflow.com/questions/3952210/android-thread-problem-why-ui-still-blocks-when-i-have-used-a-worker-thread) is the reason it still blocks the main thread.

**Comment by sojanpr** [comment]
@AndrazP  Thank you very much for pointing this out. We have added PR https://github.com/BranchMetrics/android-branch-deep-linking/pull/578 to fix this issue. Will release once the QA is finished

**Comment by sojanpr** [comment]
@AndrazP  The fix is released with v2.18.1
