### ISSUE TITLE
IllegalStateException: DeviceInfo.getDefaultBrowserAgent

### ISSUE THREAD

**Issue by AndrazP** [BranchMetrics/android-branch-deep-linking#583]
Hi,

We see some Branch SDK related crashes in our logs.
Method DeviceInfo.getDefaultBrowserAgent causes IllegalStateException. It's triggered by BranchUniversalObject.registerView.

Branch SDK version: 2.18.1

Whole stack trace:
[IllegalStateException_DeviceInfo.getDefaultBrowserAgent-stack_trace.txt](https://github.com/BranchMetrics/android-branch-deep-linking/files/2105817/IllegalStateException_DeviceInfo.getDefaultBrowserAgent-stack_trace.txt)

<img width="1608" alt="screen shot 2018-06-15 at 13 04 47" src="https://user-images.githubusercontent.com/1963904/41465058-c4b687e2-709c-11e8-9126-eaf752ba0671.png">

**Comment by sojanpr** [comment]
@AndrazP Thanks for the logs. We are working on it and update asap.

**Comment by Sarkar** [comment]
Hi @AndrazP , can you let us know if this is still an issue, after the update?

**Comment by AndrazP** [comment]
Hi @Sarkar,
I was not aware that a new version is available. We will include it our next release.
For now I'm closing this issue.
Thanks!
