### ISSUE TITLE
How can I open a link posted within my app?

### ISSUE THREAD

**Issue by exegonmar** [BranchMetrics/android-branch-deep-linking#590]
If a post a link whiten my app the referring is empty. Is there a way to launch a link posted within the app?

**Comment by sojanpr** [comment]
@exegonmar Are you trying to open a link to your app from your app itself? If so you can use the following snippet
```
Intent resultIntent = new Intent(this, TargetClass.class);
intent.putExtra("branch","http://your.app.link");
intent.putExtra("branch_force_new_session",true);
context.startActivity(resultIntent)
```

**Comment by exegonmar** [comment]
@sojanpr Yes indeed, links are posted as textview with tag android:autoLink="web"

**Comment by sojanpr** [comment]
@exegonmar please intercept the click on the textview and call the above snippet to restart you app with deep link to the link clicked.

**Comment by sojanpr** [comment]
@exegonmar Can you please provide some more info? What do you see when you start your activity with the new intent?  Are you sure you set the new intent to your activity?
Can you please share the code that you are using. It would be much easier.
