### ISSUE TITLE
Branch not respected the timeout

### ISSUE THREAD

**Issue by bayrontq** [BranchMetrics/android-branch-deep-linking#605]
Hello!

The branch.initSession has not respected the timeout of 3000 ms and nor the timeout defined with branch.setNetworkTimeout.

Depending on the quality of the internet it takes longer than 15 seconds.

I use Banch SDK 2.19.0

**Comment by StuStirling** [comment]
I am also seeing this issue running Branch SDK 2.18.0. It can run indefinitely when there is no internet.

**Comment by sojanpr** [comment]
This is a known issue with URLConnection class bug in Java. If you check the URLConnection time out implementation, the time out is repeated per each DNS resolved IP addresses.

Branch is using URLConnection by default for networking.

Luckily Branch SDK provides support for your own network implementation in case you want to have more control or you want to use any other libraries like Volley OKHttp etc.

Here is how you add a custom network interface
https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/Branch-SDK/src/io/branch/referral/Branch.java#L449

Here is the abstract interface
https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/Branch-SDK/src/io/branch/referral/network/BranchRemoteInterface.java

**Comment by StuStirling** [comment]
I have created a simple OkHttp replacement to be able to manage the timeouts. Seems to work ok.

```

class OkhttpBranchNetworkInterface : BranchRemoteInterface() {
    private val okHttpClient = OkHttpClient.Builder()
            .readTimeout(3, TimeUnit.SECONDS)
            .writeTimeout(3, TimeUnit.SECONDS)
            .connectTimeout(3, TimeUnit.SECONDS)
            .build()

    override fun doRestfulGet(url: String): BranchResponse {
        val request = Request.Builder()
                .url(url)
                .build()

        return handleNetworkRequest(request)
    }

    override fun doRestfulPost(url: String, payload: JSONObject): BranchResponse {
        val request = Request.Builder()
                .url(url)
                .post(RequestBody.create(MediaType.parse("application/json"),payload.toString()))
                .build()

        return handleNetworkRequest(request)
    }

    private fun handleNetworkRequest(request: Request) : BranchResponse {
        return try {
            val response = okHttpClient.newCall(request).execute()
            BranchResponse(response.body().toString(),response.code())
        } catch (exception: Exception) {
            if (exception is UnknownHostException) throw BranchRemoteException(BranchError.ERR_BRANCH_NO_CONNECTIVITY)
            else if (exception is SocketTimeoutException) throw BranchRemoteException(BranchError.ERR_BRANCH_REQ_TIMED_OUT)
            BranchResponse(null,0)
        }
    }
}
```

**Comment by csalmi-branch** [comment]
@StuStirling Are you still experiencing this issue?

**Comment by csalmi-branch** [comment]
Due to the age of this issue, I am closing this now. If you are encountering this problem still, please reach out to our support team (support.branch.io) or open a new github issue and we would be happy to help you out!
