### ISSUE TITLE
Shared links are not shown as hyperlinks in Samsung native email client.

### ISSUE THREAD

**Issue by bhagyae5308** [BranchMetrics/android-branch-deep-linking#606]
I used this sample app. I have shared the link from Samsung native email client. After that I opened the email in the same email client in a different device. The branch link is not highlighted and not tappable. It works properly with Gmail.
PFA the screenshot for reference.
![screenshot_20180824-135205_email](https://user-images.githubusercontent.com/8956142/44573771-2ced6d00-a7a5-11e8-8395-592b0dd70135.jpg)

**Comment by Psrinath-branch** [comment]
Hi @bhagyae5308 - Are you still experiencing this issue? If yes, can you provide more details about your integration?

Thanks!

**Comment by csalmi-branch** [comment]
Due to the age of this issue, I am closing this now. If you are encountering this problem still, please reach out to our support team (support.branch.io) or open a new github issue and we would be happy to help you out!
