### ISSUE TITLE
branch.io link is not working on MI devices when link shared by SMS. 

### ISSUE THREAD

**Issue by Bhaii** [BranchMetrics/android-branch-deep-linking#609]
Hi,
my branch.io link is not working on MI devices when link shared by SMS. The same link is working fine when shared by email on same device.  Screenshot attached.

![mi](https://user-images.githubusercontent.com/42796753/44769563-ac52b600-ab82-11e8-8121-e2a6c5a494fa.png)

**Comment by Psrinath-branch** [comment]
Hi @Bhaii -  Are you still experiencing this issue? If yes, can you provide more details around it?

**Comment by csalmi-branch** [comment]
Due to the age of this issue, I am closing this now. If you are encountering this problem still, please reach out to our support team (support.branch.io) or open a new github issue and we would be happy to help you out!

**Comment by deepti1408** [comment]
this issue still persists . Do you have any solution?
