### ISSUE TITLE
On 400 or 409, error handler in the request queue is not invoked, app start hangs.

### ISSUE THREAD

**Issue by jstaahl** [BranchMetrics/android-branch-deep-linking#616]
We are calling `branch.initSession()` in our main Acitivity's `onStart()`, but our `BranchReferralInitListener` callback is *never being invoked - either with or without an error*. Looking through Branch.java, it appears that on 400 or 409, our handler is not being invoked due to the request being removed from the queue before trying to handle the error: https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/Branch-SDK/src/io/branch/referral/Branch.java#L2849

```
  if (status == 400 || status == 409) {
    requestQueue_.remove(thisReq_);
    if (thisReq_ instanceof ServerRequestCreateUrl) {
      ((ServerRequestCreateUrl) thisReq_).handleDuplicateURLError();
    } else {
      Log.i("BranchSDK", "Branch API Error: Conflicting resource error code from API");
      handleFailure(0, status);
    }
  }
```

You can see here that the request is being removed from the queue before `handleFailure()` is called. So, when `handleFailure()` is called, the queue is already empty, and our callback is never invoked. So, on our end, it looks like branch is still initializing the session... indefinitely.

It seems to me that the code should be changed to:
```
  if (status == 400 || status == 409) {
    if (thisReq_ instanceof ServerRequestCreateUrl) {
      ((ServerRequestCreateUrl) thisReq_).handleDuplicateURLError();
    } else {
      Log.i("BranchSDK", "Branch API Error: Conflicting resource error code from API");
      handleFailure(0, status);
    }
    requestQueue_.remove(thisReq_);
  }
```

As a workaround, I guess I will need to implement a timeout on our end that eventually abandons the result of the `branch.initSession()` call after some amount of time has elapsed.

As a side note, the reason I am reaching this block is due to a 400 from "v1/install".

**Comment by Sarkar** [comment]
@jstaahl -- confirming that upgrading to the latest version of the SDK fixed this. I'll close, but please re-open if you feel like it's not solved.

**Comment by matthew-niemann** [comment]
@Sarkar I can confirm that this issue still exists in 3.1.1. The `BranchReferralInitListener` is never invoked due to the request being dumped from the `requestQueue_` before being evaluated by `handleFailure`. The PR by @sojanpr will certainly rectify this.

**Background**:
I am receiving the error due to a HTTP 400 response during the initialisation phase. I am actually not sure why this error code is being returned in the first place, and it seems it only occurs in certain territories. The only logs I receive are:
```
I/BranchRemoteInterfaceUrlConnection: JSON exception: End of input at character 1 of {
I/BranchSDK: Branch API Error: Conflicting resource error code from API
```
... and nothing else

**Comment by QuentinGuillout** [comment]
Same here, receiving

**Comment by squeeish** [comment]
This is mine

```
posting to https://api2.branch.io/v1/open
Post value = ... returned {"error":{"instrumentation":[],"metadata":[],"android_app_link_url":"doesn't pass regex"}}
Branch API Error: Conflicting resource error code from API
```

**Comment by jonneymendoza** [comment]
Hi. has this been fixed yet?

**Comment by maraisf** [comment]
We had the issue on: 
`io.branch.sdk.android:library:3.2.0`
`io.branch.sdk.android:library:4.0.0`

I have noticed that on our android app when your `android_app_link_url` **has any spaces** you will receive the regex error:
```
I/BranchSDK: returned {"error":{"instrumentation":[],"metadata":[],"android_app_link_url":"doesn't pass regex"}}

I/BranchSDK: Branch API Error: Conflicting resource error code from API
```


Also as a result of that, as mentioned above the 
`Branch.getInstance().initSession((referringParams, error)` callback is never called.

#### Solution1
Make sure you encode your `android_app_link_url` spaces with `%20`

#### Solution2
Wrap the branch `initSession()` in a timeout. Will timeout afte 3s and continue app startup.

```
        // branch timeout
        Runnable startTheAppTask = () -> {
            Timber.e("Branch.getInstance().initSession() has not responded. Please check for related Branch errors!");

            // continue with loading your app here
        };
        ScheduledExecutorService executor = Executors.newSingleThreadScheduledExecutor();
        ScheduledFuture<?> branchTimeoutSchedule = executor.schedule(startTheAppTask, 3, TimeUnit.SECONDS);


        // branch init
        Branch.getInstance().initSession((referringParams, error) -> {
            // did get a response, cancel timeout
            branchTimeoutSchedule.cancel(true);

            // normal operation handling the callback
       }, getActivity().getIntent().getData(), getActivity());

```

**Comment by Danyaga** [comment]
I think the issue is still there also in the last version of their SDK ().

**Comment by AshrafRizvi01** [comment]
When trying to generate URL i am getting the same error:

`I/BranchSDK: Branch API Error: Conflicting resource error code from API`

Any progress on this?

**Comment by sudansh** [comment]
I am still experiencing this issue.
`Branch API Error: Conflicting resource error code from API` I am on the latest build 5.0.1. Any update on this?

**Comment by PratikGondil** [comment]
Branch.io returns 
Branch API Error: Conflicting resource error code from API

After lot of research i found the solution just to enable test mode to true like below.

     <meta-data
            android:name="io.branch.sdk.TestMode"
            android:value="true" />
