### ISSUE TITLE
StrictMode Policy Violation

### ISSUE THREAD

**Issue by Pato94** [BranchMetrics/android-branch-deep-linking#632]
We just upgraded our targetSDKVersion and started to see some violations to our StrictMode policy. I think this is related to [the new untagged socket policy](https://developer.android.com/reference/kotlin/android/os/StrictMode.VmPolicy.Builder#detectUntaggedSockets%28%29)

We'd love to see a fix for this since we don't want to change our policies, and the warnings are pretty annoying

**Comment by Sarkar** [comment]
@Pato94, thanks for the heads up. Can you confirm you're setting `targetSDKVersion` to 28? If not, can you tell us which version you're targeting?

**Comment by Pato94** [comment]
Yep, it's at 28

**Comment by Sarkar** [comment]
Thanks, @Pato94. We'll be looking into this.

**Comment by UnicycleBrigadier** [comment]
Just ran into this, updated to v3.0.1 and saw that there is some socket tagging in place. Still see a strict mode violation for an untagged socket originating from `io.branch.referral.UniversalResourceAnalyser$UrlSkipListUpdateTask.doInBackground(UniversalResourceAnalyser.java:166)`

Also noticed that while `BranchRemoteInterfaceUrlConnection.doRestfulPost()` is setting a tag there is not an equivalent call in `doRestfulGet()`. Not seeing any strict mode violations referencing that so it may already be covered if those are running on the same thread, just wanted to call out that observation.

**Comment by Psrinath-branch** [comment]
Hi @UnicycleBrigadier - are you still facing the same issue?

**Comment by csalmi-branch** [comment]
Since this issue has been fixed in a previous deploy, I am closing this now. If you are encountering this problem still, please reach out to our support team (support.branch.io) or open a new github issue and we would be happy to help you out!
