### ISSUE TITLE
Reports of user deeplinks not working

### ISSUE THREAD

**Issue by hermant2** [BranchMetrics/android-branch-deep-linking#639]
We've been facing a rare, reoccurring issue with our deeplinks, which we recently started using to verify a user's phone number.  Users have reported that they are clicking the link, it's directing them to our app, but their phone number still is not being verified.  We log all of our API calls, so we are sure that the api is not being hit, and more recently, we started logging our branch link parameters as well.  All of the users that report this issue have this json in their branch link data:

`"{\"+clicked_branch_link\":false,\"+is_first_session\":false}"`

We have not been able to reproduce this issue on our end.  We have also been testing the exact same links that our users are clicking, and have received the correct branch data from them every time.  The issue has occurred on a variety of devices/OS versions, so we're pretty uncertain as to what might be causing this.  We're seeking more information from the handful of users that have been having this issue.  If we receive anymore helpful information from them I will follow up with it in this issue.  Thank you.

**Comment by hermant2** [comment]
Not sure if this is what is causing our issue, but I disabled google chrome and started testing the links out with other browsers installed.

Mozilla Firefox:
Clicking the link briefly opens the branch generated web page (the one that has the button at the bottom that says "Get the app") and then launches the playstore. When I click "Open" from there, the branch data is not present. 
However, if i quickly click "Get the app" in the generated web page, then our app immediately launches with the branch data present.  

Microsoft Edge:
Tries to open the branch generated web page, but gets hung up and never does

DuckDuckGo:
Launches the webpage and immediately displays a dialog to Open in another app. There are two options here, "Cancel" and "Open External App".  Clicking Open External app launches our app's page in the playstore, and the branch data is not present when we click open from there.  

However, if I instead click "Cancel" on the dialog that immediately displays, and then click "Get the app" at the bottom of the webpage, the same dialog displays again.  When ?I click "Open External App" from there, it launches the playstore. Then the branch data is present when I click open from there.

**Comment by hermant2** [comment]
One of the users who was having this issue sent us a video.  They were clicking from the Samsung messages app, which has it's own browser.  I tested it on my own device and am now able to reproduce the error

**Comment by Psrinath-branch** [comment]
Hi @hermant2 -are you still facing the same issue?

**Comment by csalmi-branch** [comment]
Due to the age of this issue, I am closing this now. If you are encountering this problem still, please reach out to our support team (support.branch.io) or open a new github issue and we would be happy to help you out!
