### ISSUE TITLE
Links in Readme are redirecting to iOS documentation

### ISSUE THREAD

**Issue by tir38** [BranchMetrics/android-branch-deep-linking#661]
E.g. `https://dev.branch.io/getting-started/integration-testing/guide/android/` is redirecting to `https://docs.branch.io/pages/apps/ios/#simulate-an-install` Probably need to update Readme to latest Android urls.

**Comment by Psrinath-branch** [comment]
Hi @tir38 - Thanks for bringing this to our attention. I'll have our documentation team fix this issue. 

Thanks!

**Comment by csalmi-branch** [comment]
The links in the readme have been updated.
