### ISSUE TITLE
Sending Branch Deeplink via push notification not translating into URI for routing

### ISSUE THREAD

**Issue by Odaym** [BranchMetrics/android-branch-deep-linking#684]
Hi, I'm following this the steps required to be able to handle Branch Deeplinks sent in push notifications: [https://github.com/BranchMetrics/android-branch-deep-linking#deeplink-via-push-notification](url)

What I'm doing is heading over to Mixpanel and sending the push from over there to a specific device, the following is a push that includes a **Branch URI** and it works when I try to route it. Meaning I am able to read the URI as `uri.host` and determine what to do with it accordingly, using the rest of that URI's params to know exactly what to do.

`{"mp_message": "This is a message", "branch": "my-app://search/create/?make_id=chevrolet&year_min=2007&price_max=230000"}`

**Now for actual URL's (deeplinks) being sent as a part of the message:**

`{"mp_message": "This is a message", "key_name": "https://my.app-app.link/JYYFLYtG8T"}`

This push is received successfully as well of course, but the handling is the problem, the above documentation from Branch states that I have to pass that link, as is, to my result intent under the key `branch` so that Branch may magically turn it into a URI that I can parse like I did with the payload above?

```
Intent resultIntent = new Intent(this, TargetClass.class);
intent.putExtra("branch","http://bnc.lt/testlink");
.....
PendingIntent resultPendingIntent =  PendingIntent.getActivity(this, 0, resultIntent, PendingIntent.FLAG_UPDATE_CURRENT);
```
And this is just what I do as it happens that I re-send the contents of that push notification as my own local notification by doing the following:

```
if (routerKeyLink != null && routerKeyLink.contains("http")) {
                clickedIntent.putExtra("branch", routerKeyLink)
}

.....
val actionIntent = PendingIntent.getActivity(
                this,
                0,
                clickedIntent,
                PendingIntent.FLAG_UPDATE_CURRENT
            )

            val notification = NotificationCompat.Builder(
                this,
                getString(R.string.car_updates_notification_channel_id)
            )
                .setContentIntent(actionIntent)
           
..... ETC.
```
And the push is successfully sent, clicking on it though does not produce anything new, or turn the URL into a URI that i can parse like the above, it just remains as is: `https://my.app-app.link/JYYFLYtG8T` This is something I cannot treat in the same fashion as I do above of course, isn't this what is supposed to happen when I follow the above docs?

My Branch Links Host value is correct and matches the URL i am sending in the faulty push, I don't know what else to do here.

Branch lib version `3.0.1`

**Comment by Odaym** [comment]
nothing?

**Comment by code-crusher** [comment]
Hey @Odaym, we released a new version of the Android SDK v3.1.1 https://github.com/BranchMetrics/android-branch-deep-linking/releases/tag/3.1.1 to address the known issue with Push Notification deep linking. 

You can continue to use the current implementation, but with the new update, you'll receive the deep link data inside the `initSession()` method when you click the notification with Branch link under `branch` key in the intent, as you get the data with normal deep links. This should help resolve the issue you are facing.

**Comment by Odaym** [comment]
Thanks, I hope you can leave this issue open until I try this tomorrow 👍

**Comment by Odaym** [comment]
Seems to have worked as you mentioned, thank you again!
