### ISSUE TITLE
Secure Branch Key in XML?

### ISSUE THREAD

**Issue by sirvon** [BranchMetrics/android-branch-deep-linking#74]
So, the branch key is the gateway to the underlying system,
if one's app is designed to use branch as a clearinghouse for pts/invite code access
that would make that key highly valuable.

The android manifest can be seen by anyone with sense...

Can you suggest ways to access the key within the manifests' xml but from outside the application itself...say an external file?

thanks

**Comment by aaustin** [comment]
Hey @sirvon - this is why we've designed the public/private key system on Branch. You'll notice that all [API calls](https://github.com/BranchMetrics/Branch-Public-API) require the use of the Branch secret key for authentication. What are your thoughts on that?

**Comment by sirvon** [comment]
on android, I don't use the secret key in any fashion to interact with the branch points system.

All i'm using is the keys required by the manifest. 
Someone with knowledge can get that key from the manifest using
[Android Manifest App][1]

And make a quick app, with branch's library and my apps key from the manifest and start emulating or adding/subtracting value from my branch "bank acct" per se.

How can I use the secret key within an android or ios app?

[1]: https://play.google.com/store/apps/details?id=jp.susatthi.ManifestViewer&hl=en

**Comment by SleeplessByte** [comment]
You can't. 

Branch should probably opt-in to do SHA match on a signature level such as Facebook and Google. What you do is enter the SHA-1 of your finalized app's key+store to Branch and they would verify that the requests are made with the same value. Because one can only get this value with access to the keystore and its contents, these are actually safe.

**Comment by sojanpr** [comment]
@sirvon With sdk v2.0.0 we have given option to keep your Branch keys  secure inside string resource vs adding it in manifest. Thanks for helping us to improve the SDK

**Comment by SleeplessByte** [comment]
Putting it in a string resource is just as insecure as putting it in the manifest.

**Comment by sojanpr** [comment]
@SleeplessByte agree that you can get the res items for an application if you know the package name and resource name for the resource item. Just wanted to hide it from Manifest viewer applications which easily shows the keys

**Comment by sirvon** [comment]
is this any more secure...

```grade

resValue "string", "facebook_app_id", "\"${props.getProperty("facebookAppId_loqoo")}\""

```

put it in an external file, then ref it in gradle.build.........

**Comment by sojanpr** [comment]
@sirvon Thank you very much for your comment. Certainly this looks  more secure. Will check and add an option for specifying key from gradle. Thanks for helping to improve Branch SDK

**Comment by mauricegavin** [comment]
@sojanpr 
I would like to refer to the Branch key's through build.gradle. As mentioned by @sirvon above, it allows for more secure storage of keys. At present the only two options seem to be putting them in the AndroidManifest.xml or strings.xml. Both of these approaches make it difficult to keep the keys out of source control.

```
11-02 00:36:48.781 23593-23593/com.app.debug I/BranchSDK: Branch Warning: Please enter your branch_key in your project's Manifest file!
11-02 00:36:49.051 23593-23593/com.app.debug I/BranchSDK: Branch Warning: Please enter your branch_key in your project's res/values/strings.xml!
```
Ideally I would like to fetch the key from myself and supply it to the initialiser at runtime, as would be standard for most services. Have you any plans to support this approach?

**Comment by EvangelosG** [comment]
Hi Maurice. [We have a function for this](https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/Branch-SDK/src/io/branch/referral/Branch.java#L463)! Please make sure to call  `Branch.getAutoInstance(this);` in your application class, and in your activity before calling init, use: `Branch branch = Branch.getInstance(context, "MY_KEY");` We're introducing a more elegant way to do this in the future, but for now this is the solution.

**Comment by AmitPandya007** [comment]
> getAutoInstance

As per the docs, it is showing only below two methods for the getAutoInstance() method:

1.  public static Branch getAutoInstance(Context context) {}
2.  public static Branch getAutoInstance(Context context, boolean isReferrable) {}

The third method which you have explained is it removed from the Branch.java file?
Please clear my query about the branch key.
